_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.11724372737627752
aug_joint_noise_std:
    value: 0.006946987331502911
aug_rotation_range:
    value: 25.15079263764563
aug_scale_max:
    value: 1.2384781728690175
aug_scale_min:
    value: 0.7430311110714638
aug_translation_std:
    value: 0.04948687608074635
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.4004990659245789
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.11724372737627752
            joint_noise_std: 0.006946987331502911
            rotation_range: 25.15079263764563
            scale_range:
                - 0.7430311110714638
                - 1.2384781728690175
            translation_std: 0.04948687608074635
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.1
ema_decay:
    value: 0.998462520088996
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_6zcnxiql_20250603_235227
freeze_layers:
    value: 8
grad_clip:
    value: 1.7963701531872966
gradient_checkpointing:
    value: false
hidden_dim:
    value: 512
learning_rate:
    value: 0.008703577371001784
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.11348707628684668
            diversity: 0.006679999495000387
            hand_coarse: 1.068904846608568
            hand_refined: 1.625467888304185
            kl: 0.0008926249602664782
            object_position: 1.4286819268317008
            object_rotation: 0.4761981678552279
            physics: 0.08651979370518703
            reprojection: 0.6217433293049628
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.11348707628684668
loss_weight_diversity:
    value: 0.006679999495000387
loss_weight_hand_coarse:
    value: 1.068904846608568
loss_weight_hand_refined:
    value: 1.625467888304185
loss_weight_kl:
    value: 0.0008926249602664782
loss_weight_object_position:
    value: 1.4286819268317008
loss_weight_object_rotation:
    value: 0.4761981678552279
loss_weight_physics:
    value: 0.08651979370518703
loss_weight_reprojection:
    value: 0.6217433293049628
lr_mult_new_encoders:
    value: 0.7103406205612703
lr_mult_pretrained:
    value: 0.009321986135699631
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.1
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.4004990659245789
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/6zcnxiql
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 2.891385797666381e-06
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.998462520088996
        grad_clip: 1.7963701531872966
        learning_rate: 0.008703577371001784
        log_freq: 100
        min_lr: 2.891385797666381e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.7103406205612703
            pretrained: 0.009321986135699631
        num_epochs: 20
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0014043981970670164
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0014043981970670164
