_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.1493777305449825
aug_joint_noise_std:
    value: 0.005108754006613319
aug_rotation_range:
    value: 28.77395355243277
aug_scale_max:
    value: 1.1095171740796708
aug_scale_min:
    value: 0.8590725381065165
aug_translation_std:
    value: 0.04579552672123367
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.5868826138360677
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.1493777305449825
            joint_noise_std: 0.005108754006613319
            rotation_range: 28.77395355243277
            scale_range:
                - 0.8590725381065165
                - 1.1095171740796708
            translation_std: 0.04579552672123367
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9916538285947174
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_q6v86mw6_20250603_231036
freeze_layers:
    value: 8
grad_clip:
    value: 0.9906123825045154
gradient_checkpointing:
    value: true
hidden_dim:
    value: 512
learning_rate:
    value: 5.986760278136021e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.25922051594049256
            diversity: 0.017923628988968165
            hand_coarse: 0.6059454465774853
            hand_refined: 1.7745694003060812
            kl: 0.0003935177370148232
            object_position: 1.7400207816094897
            object_rotation: 0.7263214297613676
            physics: 0.08592545252574364
            reprojection: 0.3512992538773838
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.25922051594049256
loss_weight_diversity:
    value: 0.017923628988968165
loss_weight_hand_coarse:
    value: 0.6059454465774853
loss_weight_hand_refined:
    value: 1.7745694003060812
loss_weight_kl:
    value: 0.0003935177370148232
loss_weight_object_position:
    value: 1.7400207816094897
loss_weight_object_rotation:
    value: 0.7263214297613676
loss_weight_physics:
    value: 0.08592545252574364
loss_weight_reprojection:
    value: 0.3512992538773838
lr_mult_new_encoders:
    value: 0.35867453364025204
lr_mult_pretrained:
    value: 0.03874664761908114
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.3
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.5868826138360677
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/q6v86mw6
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 6.793458844569388e-06
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.9916538285947174
        grad_clip: 0.9906123825045154
        learning_rate: 5.986760278136021e-05
        log_freq: 100
        min_lr: 6.793458844569388e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.35867453364025204
            pretrained: 0.03874664761908114
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.017035186762230033
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.017035186762230033
