_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.21143936012068065
aug_joint_noise_std:
    value: 0.008753858303479845
aug_rotation_range:
    value: 15.588470867978824
aug_scale_max:
    value: 1.2384472898215428
aug_scale_min:
    value: 0.834462118595794
aug_translation_std:
    value: 0.053740615156887744
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.3613346546674431
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.21143936012068065
            joint_noise_std: 0.008753858303479845
            rotation_range: 15.588470867978824
            scale_range:
                - 0.834462118595794
                - 1.2384472898215428
            translation_std: 0.053740615156887744
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.9937793697728294
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_0olr6z5x_20250603_231259
freeze_layers:
    value: 10
grad_clip:
    value: 1.1454475246754854
gradient_checkpointing:
    value: true
hidden_dim:
    value: 1024
learning_rate:
    value: 0.001027118489244074
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.41983508684327
            diversity: 0.008595273414313287
            hand_coarse: 1.2392696414960154
            hand_refined: 2.4455890872147843
            kl: 0.0002233132711235925
            object_position: 0.916683208242047
            object_rotation: 0.63912806374987
            physics: 0.06845821314851265
            reprojection: 0.9799459987330617
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.41983508684327
loss_weight_diversity:
    value: 0.008595273414313287
loss_weight_hand_coarse:
    value: 1.2392696414960154
loss_weight_hand_refined:
    value: 2.4455890872147843
loss_weight_kl:
    value: 0.0002233132711235925
loss_weight_object_position:
    value: 0.916683208242047
loss_weight_object_rotation:
    value: 0.63912806374987
loss_weight_physics:
    value: 0.06845821314851265
loss_weight_reprojection:
    value: 0.9799459987330617
lr_mult_new_encoders:
    value: 0.7328620389338929
lr_mult_pretrained:
    value: 0.0012097557596924856
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.2
        freeze_layers: 10
        hidden_dim: 1024
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.3613346546674431
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/0olr6z5x
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 5.947176578214244e-07
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9937793697728294
        grad_clip: 1.1454475246754854
        learning_rate: 0.001027118489244074
        log_freq: 100
        min_lr: 5.947176578214244e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.7328620389338929
            pretrained: 0.0012097557596924856
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.009609830317528637
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.009609830317528637
