_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.19220487261913152
aug_joint_noise_std:
    value: 0.009600602491038937
aug_rotation_range:
    value: 23.940096742711468
aug_scale_max:
    value: 1.1158639314140055
aug_scale_min:
    value: 0.7606488838302562
aug_translation_std:
    value: 0.07249747903813702
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.6378520113538972
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.19220487261913152
            joint_noise_std: 0.009600602491038937
            rotation_range: 23.940096742711468
            scale_range:
                - 0.7606488838302562
                - 1.1158639314140055
            translation_std: 0.07249747903813702
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9923175253047964
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_41q6ramh_20250603_231411
freeze_layers:
    value: 8
grad_clip:
    value: 1.5255399766612094
gradient_checkpointing:
    value: true
hidden_dim:
    value: 768
learning_rate:
    value: 3.640481450400132e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.467335393613467
            diversity: 0.001523630429129042
            hand_coarse: 1.2760059288963053
            hand_refined: 1.4568681993984125
            kl: 0.0016606134415524732
            object_position: 0.8236171863535826
            object_rotation: 0.5162648616701881
            physics: 0.15232229734666833
            reprojection: 0.901133052349674
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.467335393613467
loss_weight_diversity:
    value: 0.001523630429129042
loss_weight_hand_coarse:
    value: 1.2760059288963053
loss_weight_hand_refined:
    value: 1.4568681993984125
loss_weight_kl:
    value: 0.0016606134415524732
loss_weight_object_position:
    value: 0.8236171863535826
loss_weight_object_rotation:
    value: 0.5162648616701881
loss_weight_physics:
    value: 0.15232229734666833
loss_weight_reprojection:
    value: 0.901133052349674
lr_mult_new_encoders:
    value: 0.7518471368449801
lr_mult_pretrained:
    value: 0.07275816784158473
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.3
        freeze_layers: 8
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.6378520113538972
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/41q6ramh
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 4.869651836083945e-06
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.9923175253047964
        grad_clip: 1.5255399766612094
        learning_rate: 3.640481450400132e-05
        log_freq: 100
        min_lr: 4.869651836083945e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.7518471368449801
            pretrained: 0.07275816784158473
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.04498676160394796
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.04498676160394796
