_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.14188335226579915
aug_joint_noise_std:
    value: 0.007085224723083008
aug_rotation_range:
    value: 6.962783046595767
aug_scale_max:
    value: 1.1099393612003243
aug_scale_min:
    value: 0.7989127002318099
aug_translation_std:
    value: 0.06213760246029974
batch_size:
    value: 32
diversity_margin:
    value: 0.019261430654951252
dropout:
    value: 0.15
fingertip_weight:
    value: 1.292593617054689
loss_weight_contact:
    value: 0.484657562364074
loss_weight_diversity:
    value: 0.032871346178819774
loss_weight_hand_coarse:
    value: 1.0946386135846584
loss_weight_hand_refined:
    value: 1.2476550127700048
loss_weight_object_position:
    value: 0.9881150050882892
loss_weight_object_rotation:
    value: 0.5889662368565898
loss_weight_physics:
    value: 0.10260366176205896
loss_weight_reprojection:
    value: 0.3649749315062255
per_joint_weighting:
    value: true
scheduler_type:
    value: cosine_warmup
