_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.24167821167805872
aug_joint_noise_std:
    value: 0.004747718578555754
aug_rotation_range:
    value: 11.52586738209753
aug_scale_max:
    value: 1.167233491917626
aug_scale_min:
    value: 0.7660066716220025
aug_translation_std:
    value: 0.02707315934571476
batch_size:
    value: 256
diversity_margin:
    value: 0.01867680441651341
dropout:
    value: 0.2
fingertip_weight:
    value: 1.8492949815456907
loss_weight_contact:
    value: 0.485605587154058
loss_weight_diversity:
    value: 0.01899006501531278
loss_weight_hand_coarse:
    value: 1.1871423363770963
loss_weight_hand_refined:
    value: 1.039581134380604
loss_weight_object_position:
    value: 0.9840380907526958
loss_weight_object_rotation:
    value: 0.49646233301544296
loss_weight_physics:
    value: 0.16126343010402694
loss_weight_reprojection:
    value: 0.4180774301316975
per_joint_weighting:
    value: true
scheduler_type:
    value: exponential
