_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2537667413175494
aug_joint_noise_std:
    value: 0.007529896298117051
aug_rotation_range:
    value: 27.276749378377616
aug_scale_max:
    value: 1.2747135619491297
aug_scale_min:
    value: 0.710450545166988
aug_translation_std:
    value: 0.06779673847853852
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.40963136926099447
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.2537667413175494
            joint_noise_std: 0.007529896298117051
            rotation_range: 27.276749378377616
            scale_range:
                - 0.710450545166988
                - 1.2747135619491297
            translation_std: 0.06779673847853852
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9954461653215124
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_93kjgpqg_20250603_231142
freeze_layers:
    value: 8
grad_clip:
    value: 0.737505234686096
gradient_checkpointing:
    value: true
hidden_dim:
    value: 768
learning_rate:
    value: 9.833813036715067e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.338944061945039
            diversity: 0.0019047134522983096
            hand_coarse: 1.871351385408368
            hand_refined: 1.3916628822278068
            kl: 0.008775172472285238
            object_position: 1.1095723264200836
            object_rotation: 0.8430101430529069
            physics: 0.06977919457432782
            reprojection: 0.9846058119645672
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.338944061945039
loss_weight_diversity:
    value: 0.0019047134522983096
loss_weight_hand_coarse:
    value: 1.871351385408368
loss_weight_hand_refined:
    value: 1.3916628822278068
loss_weight_kl:
    value: 0.008775172472285238
loss_weight_object_position:
    value: 1.1095723264200836
loss_weight_object_rotation:
    value: 0.8430101430529069
loss_weight_physics:
    value: 0.06977919457432782
loss_weight_reprojection:
    value: 0.9846058119645672
lr_mult_new_encoders:
    value: 0.5702014807626699
lr_mult_pretrained:
    value: 0.0021284398090225254
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.3
        freeze_layers: 8
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.40963136926099447
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/93kjgpqg
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 3.318381379562245e-06
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9954461653215124
        grad_clip: 0.737505234686096
        learning_rate: 9.833813036715067e-05
        log_freq: 100
        min_lr: 3.318381379562245e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.5702014807626699
            pretrained: 0.0021284398090225254
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.00532982544222039
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.00532982544222039
