_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.21741490867754276
aug_joint_noise_std:
    value: 0.003809081494097647
aug_rotation_range:
    value: 10.479292127412744
aug_scale_max:
    value: 1.1998947530677175
aug_scale_min:
    value: 0.7162502578425062
aug_translation_std:
    value: 0.02758754002794891
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.5043814938553871
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.21741490867754276
            joint_noise_std: 0.003809081494097647
            rotation_range: 10.479292127412744
            scale_range:
                - 0.7162502578425062
                - 1.1998947530677175
            translation_std: 0.02758754002794891
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.9940682208886072
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_ammfuoud_20250603_231025
freeze_layers:
    value: 10
grad_clip:
    value: 0.948159974058988
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 0.0022546480465982146
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.3241561913301767
            diversity: 0.0015188706151385738
            hand_coarse: 0.6204943174571131
            hand_refined: 2.161500743547867
            kl: 0.0001542854979337664
            object_position: 1.0418828013309935
            object_rotation: 0.6005313064662319
            physics: 0.09546994386128838
            reprojection: 0.7263694776193028
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.3241561913301767
loss_weight_diversity:
    value: 0.0015188706151385738
loss_weight_hand_coarse:
    value: 0.6204943174571131
loss_weight_hand_refined:
    value: 2.161500743547867
loss_weight_kl:
    value: 0.0001542854979337664
loss_weight_object_position:
    value: 1.0418828013309935
loss_weight_object_rotation:
    value: 0.6005313064662319
loss_weight_physics:
    value: 0.09546994386128838
loss_weight_reprojection:
    value: 0.7263694776193028
lr_mult_new_encoders:
    value: 0.4838218574233287
lr_mult_pretrained:
    value: 0.0040094927275266465
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.2
        freeze_layers: 10
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.5043814938553871
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/ammfuoud
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 9.056913813313732e-07
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9940682208886072
        grad_clip: 0.948159974058988
        learning_rate: 0.0022546480465982146
        log_freq: 100
        min_lr: 9.056913813313732e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.4838218574233287
            pretrained: 0.0040094927275266465
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.00013988553778220022
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.00013988553778220022
