_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.18498761253202775
aug_joint_noise_std:
    value: 0.005228225267098617
aug_rotation_range:
    value: 28.213922603173906
aug_scale_max:
    value: 1.1858848189536677
aug_scale_min:
    value: 0.7412578343429075
aug_translation_std:
    value: 0.025635120486965965
batch_size:
    value: 16
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.36467078492168087
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.18498761253202775
            joint_noise_std: 0.005228225267098617
            rotation_range: 28.213922603173906
            scale_range:
                - 0.7412578343429075
                - 1.1858848189536677
            translation_std: 0.025635120486965965
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.99025040244253
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_wjbpt1rw_20250603_231310
freeze_layers:
    value: 8
grad_clip:
    value: 1.2086534292568785
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 0.0012856594434368905
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.3807407289362028
            diversity: 0.004361516528289373
            hand_coarse: 1.1051734976475354
            hand_refined: 2.0630383996264037
            kl: 0.0003318139190412572
            object_position: 1.5386786657209357
            object_rotation: 0.5008826325917914
            physics: 0.19129284485720227
            reprojection: 0.3181765072055462
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.3807407289362028
loss_weight_diversity:
    value: 0.004361516528289373
loss_weight_hand_coarse:
    value: 1.1051734976475354
loss_weight_hand_refined:
    value: 2.0630383996264037
loss_weight_kl:
    value: 0.0003318139190412572
loss_weight_object_position:
    value: 1.5386786657209357
loss_weight_object_rotation:
    value: 0.5008826325917914
loss_weight_physics:
    value: 0.19129284485720227
loss_weight_reprojection:
    value: 0.3181765072055462
lr_mult_new_encoders:
    value: 0.4386050934521795
lr_mult_pretrained:
    value: 0.08967647356437573
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.3
        freeze_layers: 8
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.36467078492168087
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/wjbpt1rw
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 9.532238882165126e-07
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 16
        ema_decay: 0.99025040244253
        grad_clip: 1.2086534292568785
        learning_rate: 0.0012856594434368905
        log_freq: 100
        min_lr: 9.532238882165126e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.4386050934521795
            pretrained: 0.08967647356437573
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0004952799603173066
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0004952799603173066
