_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.29731969092342936
aug_joint_noise_std:
    value: 0.0028720025118286045
aug_rotation_range:
    value: 24.017404915230557
aug_scale_max:
    value: 1.2087614482519944
aug_scale_min:
    value: 0.7954848485440813
aug_translation_std:
    value: 0.09667767095981522
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.637486168567427
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.29731969092342936
            joint_noise_std: 0.0028720025118286045
            rotation_range: 24.017404915230557
            scale_range:
                - 0.7954848485440813
                - 1.2087614482519944
            translation_std: 0.09667767095981522
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.9954586820022624
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_petcl7w4_20250603_231205
freeze_layers:
    value: 8
grad_clip:
    value: 0.6625736514229452
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 3.3680793770419175e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.2774685476649599
            diversity: 0.002993064909175866
            hand_coarse: 1.5230812925702315
            hand_refined: 0.8602438033351542
            kl: 0.00016388731072166382
            object_position: 1.5019990254394044
            object_rotation: 0.20011422761026276
            physics: 0.1472105045432303
            reprojection: 0.4408962493476723
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.2774685476649599
loss_weight_diversity:
    value: 0.002993064909175866
loss_weight_hand_coarse:
    value: 1.5230812925702315
loss_weight_hand_refined:
    value: 0.8602438033351542
loss_weight_kl:
    value: 0.00016388731072166382
loss_weight_object_position:
    value: 1.5019990254394044
loss_weight_object_rotation:
    value: 0.20011422761026276
loss_weight_physics:
    value: 0.1472105045432303
loss_weight_reprojection:
    value: 0.4408962493476723
lr_mult_new_encoders:
    value: 0.5337204811281657
lr_mult_pretrained:
    value: 0.0013223430250830868
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.2
        freeze_layers: 8
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.637486168567427
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/petcl7w4
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 4.3751516898059433e-07
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.9954586820022624
        grad_clip: 0.6625736514229452
        learning_rate: 3.3680793770419175e-05
        log_freq: 100
        min_lr: 4.3751516898059433e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.5337204811281657
            pretrained: 0.0013223430250830868
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.001524192171000336
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.001524192171000336
