_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2032880043315039
aug_joint_noise_std:
    value: 0.0020559347517300993
aug_rotation_range:
    value: 18.60342297204751
aug_scale_max:
    value: 1.2130830945856133
aug_scale_min:
    value: 0.7740862192270527
aug_translation_std:
    value: 0.07130040815819574
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.5682959863256447
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.2032880043315039
            joint_noise_std: 0.0020559347517300993
            rotation_range: 18.60342297204751
            scale_range:
                - 0.7740862192270527
                - 1.2130830945856133
            translation_std: 0.07130040815819574
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.9962391218071786
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_sayksgqe_20250604_004709
freeze_layers:
    value: 12
grad_clip:
    value: 1.2515570238285854
gradient_checkpointing:
    value: true
hidden_dim:
    value: 768
learning_rate:
    value: 2.73670719483928e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.43598300697528136
            diversity: 0.001122412448332459
            hand_coarse: 1.577430692355308
            hand_refined: 1.131126286520266
            kl: 0.00023646457227908936
            object_position: 0.5648823953042394
            object_rotation: 0.9371406278300398
            physics: 0.1691325520708854
            reprojection: 0.7296598922643891
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.43598300697528136
loss_weight_diversity:
    value: 0.001122412448332459
loss_weight_hand_coarse:
    value: 1.577430692355308
loss_weight_hand_refined:
    value: 1.131126286520266
loss_weight_kl:
    value: 0.00023646457227908936
loss_weight_object_position:
    value: 0.5648823953042394
loss_weight_object_rotation:
    value: 0.9371406278300398
loss_weight_physics:
    value: 0.1691325520708854
loss_weight_reprojection:
    value: 0.7296598922643891
lr_mult_new_encoders:
    value: 0.3672522390136548
lr_mult_pretrained:
    value: 0.001531260238479711
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.2
        freeze_layers: 12
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.5682959863256447
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/sayksgqe
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 1.3546851011757757e-07
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9962391218071786
        grad_clip: 1.2515570238285854
        learning_rate: 2.73670719483928e-05
        log_freq: 100
        min_lr: 1.3546851011757757e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.3672522390136548
            pretrained: 0.001531260238479711
        num_epochs: 20
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0010350659287262313
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0010350659287262313
