_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.29220667036677955
aug_joint_noise_std:
    value: 0.0026471918695799364
aug_rotation_range:
    value: 13.084661774549334
aug_scale_max:
    value: 1.2098343992283431
aug_scale_min:
    value: 0.8322110304298409
aug_translation_std:
    value: 0.09673455903659818
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.37813526684339743
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.29220667036677955
            joint_noise_std: 0.0026471918695799364
            rotation_range: 13.084661774549334
            scale_range:
                - 0.8322110304298409
                - 1.2098343992283431
            translation_std: 0.09673455903659818
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9949409794549354
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_jts8c5z0_20250603_230904
freeze_layers:
    value: 12
grad_clip:
    value: 0.8215380861719292
gradient_checkpointing:
    value: false
hidden_dim:
    value: 512
learning_rate:
    value: 0.001423702564798356
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.4334945283637309
            diversity: 0.004941579327861191
            hand_coarse: 0.7283835847518398
            hand_refined: 1.857257487292802
            kl: 0.0012987518917991026
            object_position: 1.6741309001703355
            object_rotation: 0.571197111102759
            physics: 0.056215664412188615
            reprojection: 0.6886949535586444
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.4334945283637309
loss_weight_diversity:
    value: 0.004941579327861191
loss_weight_hand_coarse:
    value: 0.7283835847518398
loss_weight_hand_refined:
    value: 1.857257487292802
loss_weight_kl:
    value: 0.0012987518917991026
loss_weight_object_position:
    value: 1.6741309001703355
loss_weight_object_rotation:
    value: 0.571197111102759
loss_weight_physics:
    value: 0.056215664412188615
loss_weight_reprojection:
    value: 0.6886949535586444
lr_mult_new_encoders:
    value: 0.5374493742660302
lr_mult_pretrained:
    value: 0.09390737583535058
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.3
        freeze_layers: 12
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.37813526684339743
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/jts8c5z0
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 1.8060444956526938e-07
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.9949409794549354
        grad_clip: 0.8215380861719292
        learning_rate: 0.001423702564798356
        log_freq: 100
        min_lr: 1.8060444956526938e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.5374493742660302
            pretrained: 0.09390737583535058
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.00014676581411002812
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.00014676581411002812
