_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.22885495935963435
aug_joint_noise_std:
    value: 0.00887057908274688
aug_rotation_range:
    value: 17.56354320722656
aug_scale_max:
    value: 1.2993373332727038
aug_scale_min:
    value: 0.7213076595636079
aug_translation_std:
    value: 0.05822933180292461
batch_size:
    value: 16
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.6851288234429219
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.22885495935963435
            joint_noise_std: 0.00887057908274688
            rotation_range: 17.56354320722656
            scale_range:
                - 0.7213076595636079
                - 1.2993373332727038
            translation_std: 0.05822933180292461
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.9975168376044526
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_hp9h9e95_20250603_231327
freeze_layers:
    value: 8
grad_clip:
    value: 1.1624396826901289
gradient_checkpointing:
    value: false
hidden_dim:
    value: 1024
learning_rate:
    value: 6.270033156658626e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.18325406818510304
            diversity: 0.07173915078426885
            hand_coarse: 1.3590972856731012
            hand_refined: 0.8231161338729812
            kl: 0.001305300347050644
            object_position: 0.9456299521064412
            object_rotation: 0.5980039359813595
            physics: 0.18753239727746968
            reprojection: 0.6013834759909722
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.18325406818510304
loss_weight_diversity:
    value: 0.07173915078426885
loss_weight_hand_coarse:
    value: 1.3590972856731012
loss_weight_hand_refined:
    value: 0.8231161338729812
loss_weight_kl:
    value: 0.001305300347050644
loss_weight_object_position:
    value: 0.9456299521064412
loss_weight_object_rotation:
    value: 0.5980039359813595
loss_weight_physics:
    value: 0.18753239727746968
loss_weight_reprojection:
    value: 0.6013834759909722
lr_mult_new_encoders:
    value: 0.7022255847224972
lr_mult_pretrained:
    value: 0.0021839458065298837
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.2
        freeze_layers: 8
        hidden_dim: 1024
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.6851288234429219
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/hp9h9e95
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 2.4649359170837835e-06
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 16
        ema_decay: 0.9975168376044526
        grad_clip: 1.1624396826901289
        learning_rate: 6.270033156658626e-05
        log_freq: 100
        min_lr: 2.4649359170837835e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.7022255847224972
            pretrained: 0.0021839458065298837
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.05814702716241971
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.05814702716241971
