_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.20863069226120937
aug_joint_noise_std:
    value: 0.008721834456422686
aug_rotation_range:
    value: 24.13410496522463
aug_scale_max:
    value: 1.2280576106560577
aug_scale_min:
    value: 0.8796095011615374
aug_translation_std:
    value: 0.09076112743289796
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.4711075301496038
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.20863069226120937
            joint_noise_std: 0.008721834456422686
            rotation_range: 24.13410496522463
            scale_range:
                - 0.8796095011615374
                - 1.2280576106560577
            translation_std: 0.09076112743289796
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9987962589748474
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_i91tza4q_20250603_231417
freeze_layers:
    value: 10
grad_clip:
    value: 1.500430613583212
gradient_checkpointing:
    value: false
hidden_dim:
    value: 1024
learning_rate:
    value: 4.736732782631605e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.1960449865674502
            diversity: 0.04632666240094077
            hand_coarse: 1.927655189128116
            hand_refined: 2.294778346342901
            kl: 0.0002684780419772853
            object_position: 1.480959084620756
            object_rotation: 0.7297892606401373
            physics: 0.09700479067919351
            reprojection: 0.638827799225897
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.1960449865674502
loss_weight_diversity:
    value: 0.04632666240094077
loss_weight_hand_coarse:
    value: 1.927655189128116
loss_weight_hand_refined:
    value: 2.294778346342901
loss_weight_kl:
    value: 0.0002684780419772853
loss_weight_object_position:
    value: 1.480959084620756
loss_weight_object_rotation:
    value: 0.7297892606401373
loss_weight_physics:
    value: 0.09700479067919351
loss_weight_reprojection:
    value: 0.638827799225897
lr_mult_new_encoders:
    value: 0.7331969982415418
lr_mult_pretrained:
    value: 0.010638618345680143
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.3
        freeze_layers: 10
        hidden_dim: 1024
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.4711075301496038
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/i91tza4q
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 2.1002565920635487e-07
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.9987962589748474
        grad_clip: 1.500430613583212
        learning_rate: 4.736732782631605e-05
        log_freq: 100
        min_lr: 2.1002565920635487e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.7331969982415418
            pretrained: 0.010638618345680143
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.01214788595144408
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.01214788595144408
