_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.24072873416332177
aug_joint_noise_std:
    value: 0.009529937008253836
aug_rotation_range:
    value: 11.850053961157272
aug_scale_max:
    value: 1.1063540622408594
aug_scale_min:
    value: 0.7644951292862868
aug_translation_std:
    value: 0.026833922865553743
batch_size:
    value: 128
diversity_margin:
    value: 0.01342017526674946
dropout:
    value: 0.2
fingertip_weight:
    value: 1.6516583990615998
loss_weight_contact:
    value: 0.41876136879538794
loss_weight_diversity:
    value: 0.014198803759726849
loss_weight_hand_coarse:
    value: 1.101970213969357
loss_weight_hand_refined:
    value: 1.270577398987219
loss_weight_object_position:
    value: 1.1427668274894835
loss_weight_object_rotation:
    value: 0.4110253931919092
loss_weight_physics:
    value: 0.06265655917103757
loss_weight_reprojection:
    value: 0.38516036927387826
per_joint_weighting:
    value: false
scheduler_type:
    value: cosine
