_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.15773155110456888
aug_joint_noise_std:
    value: 0.003691473529874965
aug_rotation_range:
    value: 11.010779364916624
aug_scale_max:
    value: 1.2409787494999112
aug_scale_min:
    value: 0.7965906814691848
aug_translation_std:
    value: 0.09420152574327416
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.6948285800435399
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.15773155110456888
            joint_noise_std: 0.003691473529874965
            rotation_range: 11.010779364916624
            scale_range:
                - 0.7965906814691848
                - 1.2409787494999112
            translation_std: 0.09420152574327416
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.1
ema_decay:
    value: 0.9957791651666814
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_rzdk35ie_20250603_231136
freeze_layers:
    value: 8
grad_clip:
    value: 1.15559263435537
gradient_checkpointing:
    value: true
hidden_dim:
    value: 768
learning_rate:
    value: 0.00012590692055799863
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.376851269154996
            diversity: 0.033691792506734757
            hand_coarse: 1.1597702406399528
            hand_refined: 1.7950278429409667
            kl: 0.000487697996002883
            object_position: 1.1661993001738238
            object_rotation: 0.5662500776710959
            physics: 0.1867157502195056
            reprojection: 0.5552639474411556
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.376851269154996
loss_weight_diversity:
    value: 0.033691792506734757
loss_weight_hand_coarse:
    value: 1.1597702406399528
loss_weight_hand_refined:
    value: 1.7950278429409667
loss_weight_kl:
    value: 0.000487697996002883
loss_weight_object_position:
    value: 1.1661993001738238
loss_weight_object_rotation:
    value: 0.5662500776710959
loss_weight_physics:
    value: 0.1867157502195056
loss_weight_reprojection:
    value: 0.5552639474411556
lr_mult_new_encoders:
    value: 0.30515462621496064
lr_mult_pretrained:
    value: 0.002865894802503831
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.1
        freeze_layers: 8
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.6948285800435399
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/rzdk35ie
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 7.422355832796899e-06
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9957791651666814
        grad_clip: 1.15559263435537
        learning_rate: 0.00012590692055799863
        log_freq: 100
        min_lr: 7.422355832796899e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.30515462621496064
            pretrained: 0.002865894802503831
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.009384321651845778
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.009384321651845778
