_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2481488792130281
aug_joint_noise_std:
    value: 0.007186704297227765
aug_rotation_range:
    value: 9.146102875015517
aug_scale_max:
    value: 1.127283347621665
aug_scale_min:
    value: 0.7363965027546746
aug_translation_std:
    value: 0.05763511052072241
batch_size:
    value: 32
diversity_margin:
    value: 0.013462509827749877
dropout:
    value: 0.15
fingertip_weight:
    value: 1.664546641320347
loss_weight_contact:
    value: 0.42501301070511066
loss_weight_diversity:
    value: 0.016491990832415468
loss_weight_hand_coarse:
    value: 1.0719726946780317
loss_weight_hand_refined:
    value: 1.214857535893682
loss_weight_object_position:
    value: 0.9862662561629524
loss_weight_object_rotation:
    value: 0.31971213452405794
loss_weight_physics:
    value: 0.14321682625358045
loss_weight_reprojection:
    value: 0.5880716226980807
per_joint_weighting:
    value: true
scheduler_type:
    value: cosine
