_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.17480893671913417
aug_joint_noise_std:
    value: 0.009696475899106992
aug_rotation_range:
    value: 18.57027006589519
aug_scale_max:
    value: 1.2829156679886786
aug_scale_min:
    value: 0.7713388928760582
aug_translation_std:
    value: 0.08532430094263296
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.329497538158963
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.17480893671913417
            joint_noise_std: 0.009696475899106992
            rotation_range: 18.57027006589519
            scale_range:
                - 0.7713388928760582
                - 1.2829156679886786
            translation_std: 0.08532430094263296
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.1
ema_decay:
    value: 0.9913653435075682
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_phavvlse_20250603_230947
freeze_layers:
    value: 8
grad_clip:
    value: 1.1943943708804163
gradient_checkpointing:
    value: false
hidden_dim:
    value: 512
learning_rate:
    value: 0.0002438411242711113
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.40627365119965064
            diversity: 0.07285967824528365
            hand_coarse: 1.979747110253695
            hand_refined: 1.6563516256460766
            kl: 0.004815155240779668
            object_position: 0.8476530876857271
            object_rotation: 0.7448232328154694
            physics: 0.06087728989671717
            reprojection: 0.4539444668211567
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.40627365119965064
loss_weight_diversity:
    value: 0.07285967824528365
loss_weight_hand_coarse:
    value: 1.979747110253695
loss_weight_hand_refined:
    value: 1.6563516256460766
loss_weight_kl:
    value: 0.004815155240779668
loss_weight_object_position:
    value: 0.8476530876857271
loss_weight_object_rotation:
    value: 0.7448232328154694
loss_weight_physics:
    value: 0.06087728989671717
loss_weight_reprojection:
    value: 0.4539444668211567
lr_mult_new_encoders:
    value: 0.3443315185604678
lr_mult_pretrained:
    value: 0.008870075042276307
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.1
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.329497538158963
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/phavvlse
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 2.2032347852580365e-06
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.9913653435075682
        grad_clip: 1.1943943708804163
        learning_rate: 0.0002438411242711113
        log_freq: 100
        min_lr: 2.2032347852580365e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.3443315185604678
            pretrained: 0.008870075042276307
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.00010761474121909804
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.00010761474121909804
