_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.20310943636888357
aug_joint_noise_std:
    value: 0.009530080013215113
aug_rotation_range:
    value: 8.694687715007143
aug_scale_max:
    value: 1.1247154511130395
aug_scale_min:
    value: 0.7570057832923671
aug_translation_std:
    value: 0.04496491425723996
batch_size:
    value: 32
diversity_margin:
    value: 0.00857742615313547
dropout:
    value: 0.1
fingertip_weight:
    value: 1.3019368741495183
loss_weight_contact:
    value: 0.4156766877642591
loss_weight_diversity:
    value: 0.008101565117471843
loss_weight_hand_coarse:
    value: 0.9875216759498652
loss_weight_hand_refined:
    value: 1.1492224929705637
loss_weight_object_position:
    value: 0.8535818079076642
loss_weight_object_rotation:
    value: 0.566843593226813
loss_weight_physics:
    value: 0.15398731090259948
loss_weight_reprojection:
    value: 0.35907058088628685
per_joint_weighting:
    value: false
scheduler_type:
    value: cosine
