_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.27051885254724617
aug_joint_noise_std:
    value: 0.0026766866747430927
aug_rotation_range:
    value: 24.48157055608943
aug_scale_max:
    value: 1.2077893483310282
aug_scale_min:
    value: 0.7593003272390082
aug_translation_std:
    value: 0.02115047052324713
batch_size:
    value: 16
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.4092758221485011
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.27051885254724617
            joint_noise_std: 0.0026766866747430927
            rotation_range: 24.48157055608943
            scale_range:
                - 0.7593003272390082
                - 1.2077893483310282
            translation_std: 0.02115047052324713
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9987421583902772
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_qh9x0top_20250603_230942
freeze_layers:
    value: 12
grad_clip:
    value: 0.7126733977520318
gradient_checkpointing:
    value: false
hidden_dim:
    value: 512
learning_rate:
    value: 0.0071410990550652975
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.3316493772533965
            diversity: 0.05964226607356473
            hand_coarse: 0.5257572891678504
            hand_refined: 2.0888185195363977
            kl: 0.0009092383098027682
            object_position: 1.837888700621192
            object_rotation: 0.5897097873867208
            physics: 0.16358234739753902
            reprojection: 0.9941369223537146
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.3316493772533965
loss_weight_diversity:
    value: 0.05964226607356473
loss_weight_hand_coarse:
    value: 0.5257572891678504
loss_weight_hand_refined:
    value: 2.0888185195363977
loss_weight_kl:
    value: 0.0009092383098027682
loss_weight_object_position:
    value: 1.837888700621192
loss_weight_object_rotation:
    value: 0.5897097873867208
loss_weight_physics:
    value: 0.16358234739753902
loss_weight_reprojection:
    value: 0.9941369223537146
lr_mult_new_encoders:
    value: 0.6332987083069453
lr_mult_pretrained:
    value: 0.0027011516000807817
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.3
        freeze_layers: 12
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.4092758221485011
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/qh9x0top
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 1.9374026613214114e-07
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 16
        ema_decay: 0.9987421583902772
        grad_clip: 0.7126733977520318
        learning_rate: 0.0071410990550652975
        log_freq: 100
        min_lr: 1.9374026613214114e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.6332987083069453
            pretrained: 0.0027011516000807817
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.00022582058481242936
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.00022582058481242936
