_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.23741924575121456
aug_joint_noise_std:
    value: 0.0025371998389860035
aug_rotation_range:
    value: 10.68439733662816
aug_scale_max:
    value: 1.2996256207348131
aug_scale_min:
    value: 0.7300339538330057
aug_translation_std:
    value: 0.021318754265736404
batch_size:
    value: 32
diversity_margin:
    value: 0.00517412338179513
dropout:
    value: 0.15
fingertip_weight:
    value: 1.2204928178265348
loss_weight_contact:
    value: 0.33930153496837645
loss_weight_diversity:
    value: 0.008079244568075033
loss_weight_hand_coarse:
    value: 0.8331972487659227
loss_weight_hand_refined:
    value: 1.2009711016832536
loss_weight_object_position:
    value: 1.180005359284241
loss_weight_object_rotation:
    value: 0.3510135345790543
loss_weight_physics:
    value: 0.05348282125910096
loss_weight_reprojection:
    value: 0.4470374936561269
per_joint_weighting:
    value: true
scheduler_type:
    value: step
