_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2116481635743213
aug_joint_noise_std:
    value: 0.008005308957281472
aug_rotation_range:
    value: 7.215117594158471
aug_scale_max:
    value: 1.100725979649311
aug_scale_min:
    value: 0.8028080761140979
aug_translation_std:
    value: 0.05762551206461333
batch_size:
    value: 32
diversity_margin:
    value: 0.018879419057484068
dropout:
    value: 0.2
fingertip_weight:
    value: 1.4363620751671502
loss_weight_contact:
    value: 0.466327801733891
loss_weight_diversity:
    value: 0.020366215351413645
loss_weight_hand_coarse:
    value: 1.1293602596311332
loss_weight_hand_refined:
    value: 1.168767285419501
loss_weight_object_position:
    value: 0.9333127646058514
loss_weight_object_rotation:
    value: 0.6718733332102049
loss_weight_physics:
    value: 0.17872623840912277
loss_weight_reprojection:
    value: 0.3474821911449712
per_joint_weighting:
    value: true
scheduler_type:
    value: exponential
