_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.20141267506489152
aug_joint_noise_std:
    value: 0.002680439626393179
aug_rotation_range:
    value: 10.015607581636342
aug_scale_max:
    value: 1.1126150383543536
aug_scale_min:
    value: 0.8798647438953972
aug_translation_std:
    value: 0.06942049003610154
batch_size:
    value: 256
diversity_margin:
    value: 0.013418223036450422
dropout:
    value: 0.15
fingertip_weight:
    value: 1.944121609066864
loss_weight_contact:
    value: 0.35924868013857925
loss_weight_diversity:
    value: 0.007986228687405865
loss_weight_hand_coarse:
    value: 0.833789507603387
loss_weight_hand_refined:
    value: 1.0307574078126738
loss_weight_object_position:
    value: 0.9998394916436452
loss_weight_object_rotation:
    value: 0.35011009002677973
loss_weight_physics:
    value: 0.16867140877018613
loss_weight_reprojection:
    value: 0.6146398363308616
per_joint_weighting:
    value: true
scheduler_type:
    value: cosine_warmup
