_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2184364025990175
aug_joint_noise_std:
    value: 0.00962811375501646
aug_rotation_range:
    value: 13.603650964700162
aug_scale_max:
    value: 1.1671320368191298
aug_scale_min:
    value: 0.8444967019263695
aug_translation_std:
    value: 0.025464490743080985
batch_size:
    value: 256
diversity_margin:
    value: 0.010713958550302357
dropout:
    value: 0.3
fingertip_weight:
    value: 1.2629174645050627
loss_weight_contact:
    value: 0.3891939852444235
loss_weight_diversity:
    value: 0.03183747069760243
loss_weight_hand_coarse:
    value: 1.1038950153435334
loss_weight_hand_refined:
    value: 1.423683469188514
loss_weight_object_position:
    value: 1.1201606136496849
loss_weight_object_rotation:
    value: 0.6836847811801692
loss_weight_physics:
    value: 0.06244408968476594
loss_weight_reprojection:
    value: 0.5019078198607174
per_joint_weighting:
    value: true
scheduler_type:
    value: exponential
