_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.15362997811017162
aug_joint_noise_std:
    value: 0.005329342285962643
aug_rotation_range:
    value: 5.069891583412593
aug_scale_max:
    value: 1.1537318439275392
aug_scale_min:
    value: 0.7411049110138025
aug_translation_std:
    value: 0.08132772871444512
batch_size:
    value: 64
diversity_margin:
    value: 0.01381714008630484
dropout:
    value: 0.25
fingertip_weight:
    value: 1.2286698695967946
loss_weight_contact:
    value: 0.4073082979002376
loss_weight_diversity:
    value: 0.020172512446057795
loss_weight_hand_coarse:
    value: 0.9817804343268122
loss_weight_hand_refined:
    value: 1.272841589370095
loss_weight_object_position:
    value: 0.9149156993091098
loss_weight_object_rotation:
    value: 0.5328876198026988
loss_weight_physics:
    value: 0.08164111540866725
loss_weight_reprojection:
    value: 0.5269144519726685
per_joint_weighting:
    value: true
scheduler_type:
    value: cosine
