_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.15077555893315575
aug_joint_noise_std:
    value: 0.005754897060959795
aug_rotation_range:
    value: 13.650092757482415
aug_scale_max:
    value: 1.2143997318722524
aug_scale_min:
    value: 0.8216343380979868
aug_translation_std:
    value: 0.0792422665628094
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.3340081503939267
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.15077555893315575
            joint_noise_std: 0.005754897060959795
            rotation_range: 13.650092757482415
            scale_range:
                - 0.8216343380979868
                - 1.2143997318722524
            translation_std: 0.0792422665628094
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9956228227839512
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_jg2nwfad_20250603_231109
freeze_layers:
    value: 10
grad_clip:
    value: 1.2022742656058294
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 1.9073531897069915e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.3324868040860791
            diversity: 0.010361534264811383
            hand_coarse: 1.7860795888581862
            hand_refined: 1.0595618083915468
            kl: 0.0027167359292741295
            object_position: 0.9156110373179964
            object_rotation: 0.4000555139193219
            physics: 0.13347219680057548
            reprojection: 0.4009790929020233
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.3324868040860791
loss_weight_diversity:
    value: 0.010361534264811383
loss_weight_hand_coarse:
    value: 1.7860795888581862
loss_weight_hand_refined:
    value: 1.0595618083915468
loss_weight_kl:
    value: 0.0027167359292741295
loss_weight_object_position:
    value: 0.9156110373179964
loss_weight_object_rotation:
    value: 0.4000555139193219
loss_weight_physics:
    value: 0.13347219680057548
loss_weight_reprojection:
    value: 0.4009790929020233
lr_mult_new_encoders:
    value: 0.47895731433574834
lr_mult_pretrained:
    value: 0.003726664767827624
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.3
        freeze_layers: 10
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.3340081503939267
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/jg2nwfad
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 5.302020494198507e-06
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9956228227839512
        grad_clip: 1.2022742656058294
        learning_rate: 1.9073531897069915e-05
        log_freq: 100
        min_lr: 5.302020494198507e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.47895731433574834
            pretrained: 0.003726664767827624
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.01875894138665261
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.01875894138665261
