_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2765564787732391
aug_joint_noise_std:
    value: 0.004529892968456999
aug_rotation_range:
    value: 11.152985081535649
aug_scale_max:
    value: 1.1315827397926952
aug_scale_min:
    value: 0.8615406133649517
aug_translation_std:
    value: 0.05419225173997458
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.5108244246866465
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.2765564787732391
            joint_noise_std: 0.004529892968456999
            rotation_range: 11.152985081535649
            scale_range:
                - 0.8615406133649517
                - 1.1315827397926952
            translation_std: 0.05419225173997458
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9988804853589618
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_6clgwifd_20250604_005739
freeze_layers:
    value: 10
grad_clip:
    value: 0.89906525119522
gradient_checkpointing:
    value: true
hidden_dim:
    value: 768
learning_rate:
    value: 0.00024723758064040585
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.172067722593993
            diversity: 0.04065838879015541
            hand_coarse: 1.1310310598725712
            hand_refined: 2.0747409161298855
            kl: 0.008362115443403276
            object_position: 1.1612049140275222
            object_rotation: 0.23837671426978596
            physics: 0.06649465806758983
            reprojection: 0.47087447033947927
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.172067722593993
loss_weight_diversity:
    value: 0.04065838879015541
loss_weight_hand_coarse:
    value: 1.1310310598725712
loss_weight_hand_refined:
    value: 2.0747409161298855
loss_weight_kl:
    value: 0.008362115443403276
loss_weight_object_position:
    value: 1.1612049140275222
loss_weight_object_rotation:
    value: 0.23837671426978596
loss_weight_physics:
    value: 0.06649465806758983
loss_weight_reprojection:
    value: 0.47087447033947927
lr_mult_new_encoders:
    value: 0.6327059140051738
lr_mult_pretrained:
    value: 0.013109606326511324
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.3
        freeze_layers: 10
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.5108244246866465
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/6clgwifd
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 7.294818041106731e-07
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9988804853589618
        grad_clip: 0.89906525119522
        learning_rate: 0.00024723758064040585
        log_freq: 100
        min_lr: 7.294818041106731e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.6327059140051738
            pretrained: 0.013109606326511324
        num_epochs: 20
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.007163083102316596
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.007163083102316596
