_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.11969733494780138
aug_joint_noise_std:
    value: 0.005258888680847696
aug_rotation_range:
    value: 16.05058277726455
aug_scale_max:
    value: 1.111290402081771
aug_scale_min:
    value: 0.7445887452854033
aug_translation_std:
    value: 0.0990760494419208
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.3038479580050999
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.11969733494780138
            joint_noise_std: 0.005258888680847696
            rotation_range: 16.05058277726455
            scale_range:
                - 0.7445887452854033
                - 1.111290402081771
            translation_std: 0.0990760494419208
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.9937100428767548
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_qn0j2uy1_20250603_231400
freeze_layers:
    value: 12
grad_clip:
    value: 1.8692161670342444
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 1.136229783494136e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.14361601005319655
            diversity: 0.07513888347241036
            hand_coarse: 1.4878234167064708
            hand_refined: 1.9815080963944351
            kl: 0.00021329102388499576
            object_position: 0.8777839580889365
            object_rotation: 0.21088270999250033
            physics: 0.1932202274942829
            reprojection: 0.5534992126573486
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.14361601005319655
loss_weight_diversity:
    value: 0.07513888347241036
loss_weight_hand_coarse:
    value: 1.4878234167064708
loss_weight_hand_refined:
    value: 1.9815080963944351
loss_weight_kl:
    value: 0.00021329102388499576
loss_weight_object_position:
    value: 0.8777839580889365
loss_weight_object_rotation:
    value: 0.21088270999250033
loss_weight_physics:
    value: 0.1932202274942829
loss_weight_reprojection:
    value: 0.5534992126573486
lr_mult_new_encoders:
    value: 0.6238963764185932
lr_mult_pretrained:
    value: 0.041140403569702534
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.2
        freeze_layers: 12
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.3038479580050999
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/qn0j2uy1
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 3.961824729684651e-07
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.9937100428767548
        grad_clip: 1.8692161670342444
        learning_rate: 1.136229783494136e-05
        log_freq: 100
        min_lr: 3.961824729684651e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.6238963764185932
            pretrained: 0.041140403569702534
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.010755901533576176
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.010755901533576176
