# W&B Sweep Configuration for Advanced Manipulation Transformer
# This file defines the hyperparameter search space and optimization strategy
# Updated to match actual model structure

program: run_sweep.py
method: bayes  # Bayesian optimization for efficient search
metric:
  name: val/hand_mpjpe
  goal: minimize

# Early stopping configuration
early_terminate:
  type: hyperband
  s: 2
  eta: 3
  max_iter: 27

# Hyperparameter search space
parameters:
  # Learning rate (log scale)
  learning_rate:
    distribution: log_uniform_values
    min: 1e-5
    max: 1e-2
    
  # Batch size
  batch_size:
    values: [16, 32, 64]
    
  # Hidden dimensions
  hidden_dim:
    values: [512, 768, 1024]
    
  # Contact hidden dimensions (proportional to hidden_dim)
  contact_hidden_dim:
    values: [256, 512, 768]
    
  # Dropout rates
  dropout:
    values: [0.1, 0.2, 0.3]
    
  # Number of refinement steps
  num_refinement_steps:
    values: [1, 2, 3]
    
  # Freeze layers for DINOv2
  freeze_layers:
    values: [8, 10, 12]
    
  # Loss weights - Hand losses
  loss_weight_hand_coarse:
    distribution: uniform
    min: 0.5
    max: 2.0
    
  loss_weight_hand_refined:
    distribution: uniform
    min: 0.8
    max: 2.5
    
  # Loss weights - Object losses
  loss_weight_object_position:
    distribution: uniform
    min: 0.5
    max: 2.0
    
  loss_weight_object_rotation:
    distribution: uniform
    min: 0.2
    max: 1.0
    
  # Loss weights - Contact and physics
  loss_weight_contact:
    distribution: uniform
    min: 0.1
    max: 0.5
    
  loss_weight_physics:
    distribution: uniform
    min: 0.05
    max: 0.2
    
  # Loss weights - Regularization
  loss_weight_diversity:
    distribution: log_uniform_values
    min: 0.001
    max: 0.1
    
  loss_weight_reprojection:
    distribution: uniform
    min: 0.2
    max: 1.0
    
  loss_weight_kl:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.01
    
  # Optimizer settings
  weight_decay:
    distribution: log_uniform_values
    min: 0.0001
    max: 0.1
    
  grad_clip:
    distribution: uniform
    min: 0.5
    max: 2.0
    
  # Multi-rate learning multipliers
  lr_mult_pretrained:
    distribution: log_uniform_values
    min: 0.001
    max: 0.1
    
  lr_mult_new_encoders:
    distribution: uniform
    min: 0.3
    max: 0.8
    
  # Scheduler settings
  scheduler_T_0:
    values: [5, 10, 20]
    
  scheduler_min_lr:
    distribution: log_uniform_values
    min: 1e-7
    max: 1e-5
    
  # EMA decay
  ema_decay:
    distribution: uniform
    min: 0.99
    max: 0.999
    
  # Augmentation settings
  aug_rotation_range:
    distribution: uniform
    min: 10.0
    max: 30.0
    
  aug_scale_min:
    distribution: uniform
    min: 0.7
    max: 0.9
    
  aug_scale_max:
    distribution: uniform
    min: 1.1
    max: 1.3
    
  aug_translation_std:
    distribution: uniform
    min: 0.02
    max: 0.1
    
  aug_color_jitter:
    distribution: uniform
    min: 0.1
    max: 0.3
    
  aug_joint_noise_std:
    distribution: uniform
    min: 0.002
    max: 0.01
    
  # Memory optimization settings
  gradient_checkpointing:
    values: [true, false]
    
  checkpoint_ratio:
    distribution: uniform
    min: 0.3
    max: 0.7
    
  # Mixed precision settings
  use_amp:
    values: [true]
    
  use_bf16:
    values: [true]
    
  # Model architecture choices
  use_attention_fusion:
    values: [true, false]
    
  use_sigma_reparam:
    values: [true, false]
    
# Fixed parameters (not swept)
command:
  - ${env}
  - python
  - ${program}
  - ${args}