_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.15625996227269948
aug_joint_noise_std:
    value: 0.004316762647395508
aug_rotation_range:
    value: 11.142463402872671
aug_scale_max:
    value: 1.2621355932438194
aug_scale_min:
    value: 0.8997012304072856
aug_translation_std:
    value: 0.05028044907905016
batch_size:
    value: 16
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.6096359288584648
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.15625996227269948
            joint_noise_std: 0.004316762647395508
            rotation_range: 11.142463402872671
            scale_range:
                - 0.8997012304072856
                - 1.2621355932438194
            translation_std: 0.05028044907905016
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9951952588647838
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_lcsoqccl_20250603_231210
freeze_layers:
    value: 8
grad_clip:
    value: 1.6861565849079172
gradient_checkpointing:
    value: true
hidden_dim:
    value: 512
learning_rate:
    value: 8.431286646359808e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.2692530181612881
            diversity: 0.06384366817272566
            hand_coarse: 1.378040034159752
            hand_refined: 2.4009602611415155
            kl: 0.00015259350837112863
            object_position: 1.0871663843735844
            object_rotation: 0.31684003883092804
            physics: 0.15987581904868595
            reprojection: 0.38392991133444526
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.2692530181612881
loss_weight_diversity:
    value: 0.06384366817272566
loss_weight_hand_coarse:
    value: 1.378040034159752
loss_weight_hand_refined:
    value: 2.4009602611415155
loss_weight_kl:
    value: 0.00015259350837112863
loss_weight_object_position:
    value: 1.0871663843735844
loss_weight_object_rotation:
    value: 0.31684003883092804
loss_weight_physics:
    value: 0.15987581904868595
loss_weight_reprojection:
    value: 0.38392991133444526
lr_mult_new_encoders:
    value: 0.7943545578777917
lr_mult_pretrained:
    value: 0.001464701184374838
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.3
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.6096359288584648
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/lcsoqccl
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 1.5481285191383136e-06
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 16
        ema_decay: 0.9951952588647838
        grad_clip: 1.6861565849079172
        learning_rate: 8.431286646359808e-05
        log_freq: 100
        min_lr: 1.5481285191383136e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.7943545578777917
            pretrained: 0.001464701184374838
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0006038292308566121
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0006038292308566121
