_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.1037060385874024
aug_joint_noise_std:
    value: 0.0071957051651789
aug_rotation_range:
    value: 5.162602694339399
aug_scale_max:
    value: 1.2697262123350748
aug_scale_min:
    value: 0.8963119986047501
aug_translation_std:
    value: 0.08792948927422924
batch_size:
    value: 128
diversity_margin:
    value: 0.017817668344071086
dropout:
    value: 0.2
fingertip_weight:
    value: 1.3237605093501572
loss_weight_contact:
    value: 0.4684896866249347
loss_weight_diversity:
    value: 0.03997040807630691
loss_weight_hand_coarse:
    value: 0.8293814991830881
loss_weight_hand_refined:
    value: 1.11585968578572
loss_weight_object_position:
    value: 0.8893006286749449
loss_weight_object_rotation:
    value: 0.44808259580496296
loss_weight_physics:
    value: 0.1296545806628827
loss_weight_reprojection:
    value: 0.3373697640056881
per_joint_weighting:
    value: true
scheduler_type:
    value: step
