_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.1566150447142789
aug_joint_noise_std:
    value: 0.003390074761896596
aug_rotation_range:
    value: 11.394190559544729
aug_scale_max:
    value: 1.24322864088079
aug_scale_min:
    value: 0.8102497582785487
aug_translation_std:
    value: 0.06270522713912682
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.3949544392067774
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.1566150447142789
            joint_noise_std: 0.003390074761896596
            rotation_range: 11.394190559544729
            scale_range:
                - 0.8102497582785487
                - 1.24322864088079
            translation_std: 0.06270522713912682
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.995583996019454
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_j94n5vxc_20250603_231332
freeze_layers:
    value: 10
grad_clip:
    value: 1.4542723797754284
gradient_checkpointing:
    value: false
hidden_dim:
    value: 1024
learning_rate:
    value: 0.007066589092234128
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.1365867405841372
            diversity: 0.034551190583901055
            hand_coarse: 1.3202684349382436
            hand_refined: 1.590657275345218
            kl: 0.0006279564746487315
            object_position: 0.7320583608467106
            object_rotation: 0.26711103497624356
            physics: 0.09230198421893508
            reprojection: 0.7146212341742351
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.1365867405841372
loss_weight_diversity:
    value: 0.034551190583901055
loss_weight_hand_coarse:
    value: 1.3202684349382436
loss_weight_hand_refined:
    value: 1.590657275345218
loss_weight_kl:
    value: 0.0006279564746487315
loss_weight_object_position:
    value: 0.7320583608467106
loss_weight_object_rotation:
    value: 0.26711103497624356
loss_weight_physics:
    value: 0.09230198421893508
loss_weight_reprojection:
    value: 0.7146212341742351
lr_mult_new_encoders:
    value: 0.6208490571423018
lr_mult_pretrained:
    value: 0.06464514664186821
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.2
        freeze_layers: 10
        hidden_dim: 1024
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.3949544392067774
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/j94n5vxc
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 1.9431660999447944e-06
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.995583996019454
        grad_clip: 1.4542723797754284
        learning_rate: 0.007066589092234128
        log_freq: 100
        min_lr: 1.9431660999447944e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.6208490571423018
            pretrained: 0.06464514664186821
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.05269205795850713
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.05269205795850713
