_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.14501784095846604
aug_joint_noise_std:
    value: 0.009652444217711944
aug_rotation_range:
    value: 25.183147857118193
aug_scale_max:
    value: 1.2905283182457068
aug_scale_min:
    value: 0.7209405736220389
aug_translation_std:
    value: 0.07302047939533739
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.4872927072730111
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.14501784095846604
            joint_noise_std: 0.009652444217711944
            rotation_range: 25.183147857118193
            scale_range:
                - 0.7209405736220389
                - 1.2905283182457068
            translation_std: 0.07302047939533739
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.992022407231947
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_s5aq6nuf_20250604_003107
freeze_layers:
    value: 8
grad_clip:
    value: 0.9682979558959386
gradient_checkpointing:
    value: true
hidden_dim:
    value: 512
learning_rate:
    value: 0.0006757405204543355
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.41207527293281576
            diversity: 0.005708907511342785
            hand_coarse: 1.1934661045115438
            hand_refined: 2.211732137622958
            kl: 0.00016005446024598447
            object_position: 0.9252986266949558
            object_rotation: 0.2293852936340425
            physics: 0.14756731943035306
            reprojection: 0.4468481400175992
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.41207527293281576
loss_weight_diversity:
    value: 0.005708907511342785
loss_weight_hand_coarse:
    value: 1.1934661045115438
loss_weight_hand_refined:
    value: 2.211732137622958
loss_weight_kl:
    value: 0.00016005446024598447
loss_weight_object_position:
    value: 0.9252986266949558
loss_weight_object_rotation:
    value: 0.2293852936340425
loss_weight_physics:
    value: 0.14756731943035306
loss_weight_reprojection:
    value: 0.4468481400175992
lr_mult_new_encoders:
    value: 0.5614767702640368
lr_mult_pretrained:
    value: 0.002957132907115325
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.2
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.4872927072730111
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/s5aq6nuf
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 1.0003303464821675e-06
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.992022407231947
        grad_clip: 0.9682979558959386
        learning_rate: 0.0006757405204543355
        log_freq: 100
        min_lr: 1.0003303464821675e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.5614767702640368
            pretrained: 0.002957132907115325
        num_epochs: 20
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.03906997184875944
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.03906997184875944
