_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.20223011614688188
aug_joint_noise_std:
    value: 0.007510997204601697
aug_rotation_range:
    value: 20.205168736213636
aug_scale_max:
    value: 1.282495145222327
aug_scale_min:
    value: 0.8914704554037274
aug_translation_std:
    value: 0.08802939124246456
batch_size:
    value: 16
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.4423661551313802
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.20223011614688188
            joint_noise_std: 0.007510997204601697
            rotation_range: 20.205168736213636
            scale_range:
                - 0.8914704554037274
                - 1.282495145222327
            translation_std: 0.08802939124246456
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.1
ema_decay:
    value: 0.9964707801546302
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_0bboypas_20250604_010507
freeze_layers:
    value: 8
grad_clip:
    value: 0.5886471405940662
gradient_checkpointing:
    value: true
hidden_dim:
    value: 512
learning_rate:
    value: 0.0006637009920513706
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.35228331317256867
            diversity: 0.017093743806843142
            hand_coarse: 1.4053947252674883
            hand_refined: 1.7762792536095948
            kl: 0.0001381455760918243
            object_position: 1.651746268518689
            object_rotation: 0.8579361152266063
            physics: 0.16710034279716637
            reprojection: 0.8196461249369296
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.35228331317256867
loss_weight_diversity:
    value: 0.017093743806843142
loss_weight_hand_coarse:
    value: 1.4053947252674883
loss_weight_hand_refined:
    value: 1.7762792536095948
loss_weight_kl:
    value: 0.0001381455760918243
loss_weight_object_position:
    value: 1.651746268518689
loss_weight_object_rotation:
    value: 0.8579361152266063
loss_weight_physics:
    value: 0.16710034279716637
loss_weight_reprojection:
    value: 0.8196461249369296
lr_mult_new_encoders:
    value: 0.413866504684107
lr_mult_pretrained:
    value: 0.018995474805906146
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.1
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.4423661551313802
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/0bboypas
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 9.725246162325975e-07
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 16
        ema_decay: 0.9964707801546302
        grad_clip: 0.5886471405940662
        learning_rate: 0.0006637009920513706
        log_freq: 100
        min_lr: 9.725246162325975e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.413866504684107
            pretrained: 0.018995474805906146
        num_epochs: 20
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0002338494704439152
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0002338494704439152
