_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.18581954034603332
aug_joint_noise_std:
    value: 0.009393089237703217
aug_rotation_range:
    value: 9.202616420535252
aug_scale_max:
    value: 1.133154341941707
aug_scale_min:
    value: 0.8288241393032428
aug_translation_std:
    value: 0.047967438579376825
batch_size:
    value: 32
diversity_margin:
    value: 0.01610026324656516
dropout:
    value: 0.1
fingertip_weight:
    value: 1.8136970436953836
loss_weight_contact:
    value: 0.3615862991753752
loss_weight_diversity:
    value: 0.006863907984263211
loss_weight_hand_coarse:
    value: 0.8423130027403174
loss_weight_hand_refined:
    value: 1.079549590946522
loss_weight_object_position:
    value: 1.0845927431662084
loss_weight_object_rotation:
    value: 0.4649159372831442
loss_weight_physics:
    value: 0.15125882435016763
loss_weight_reprojection:
    value: 0.32595091712848584
per_joint_weighting:
    value: true
scheduler_type:
    value: exponential
