_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.18272536550320745
aug_joint_noise_std:
    value: 0.008944842777531867
aug_rotation_range:
    value: 7.6188328272493315
aug_scale_max:
    value: 1.2115000872294637
aug_scale_min:
    value: 0.7271504315803151
aug_translation_std:
    value: 0.03250613760391281
batch_size:
    value: 64
diversity_margin:
    value: 0.015647450030808592
dropout:
    value: 0.15
fingertip_weight:
    value: 1.3328270887721356
loss_weight_contact:
    value: 0.4607616595848366
loss_weight_diversity:
    value: 0.006782943004025081
loss_weight_hand_coarse:
    value: 1.1667574948560238
loss_weight_hand_refined:
    value: 1.079471987398663
loss_weight_object_position:
    value: 0.8314365575609373
loss_weight_object_rotation:
    value: 0.3960125487148205
loss_weight_physics:
    value: 0.0987483156108832
loss_weight_reprojection:
    value: 0.5929222857132368
per_joint_weighting:
    value: true
scheduler_type:
    value: exponential
