_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2403524326787473
aug_joint_noise_std:
    value: 0.005595120438020828
aug_rotation_range:
    value: 10.291101865943329
aug_scale_max:
    value: 1.219843974862869
aug_scale_min:
    value: 0.7742318397028845
aug_translation_std:
    value: 0.08641209077993553
batch_size:
    value: 256
diversity_margin:
    value: 0.01368127982009789
dropout:
    value: 0.1
fingertip_weight:
    value: 1.5975549051273528
loss_weight_contact:
    value: 0.2547335626561951
loss_weight_diversity:
    value: 0.025042369559691663
loss_weight_hand_coarse:
    value: 1.195629116049651
loss_weight_hand_refined:
    value: 1.018667134948572
loss_weight_object_position:
    value: 0.8641789746943428
loss_weight_object_rotation:
    value: 0.32067439636550377
loss_weight_physics:
    value: 0.1086510457503921
loss_weight_reprojection:
    value: 0.47731030230887006
per_joint_weighting:
    value: false
scheduler_type:
    value: cosine
