_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.16759573046758278
aug_joint_noise_std:
    value: 0.002488706873950082
aug_rotation_range:
    value: 12.562328793860193
aug_scale_max:
    value: 1.1107510691492466
aug_scale_min:
    value: 0.887800095174327
aug_translation_std:
    value: 0.0777552775378009
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.36272877696805167
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.16759573046758278
            joint_noise_std: 0.002488706873950082
            rotation_range: 12.562328793860193
            scale_range:
                - 0.887800095174327
                - 1.1107510691492466
            translation_std: 0.0777552775378009
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.9907507819948704
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_2yprir2j_20250603_231009
freeze_layers:
    value: 10
grad_clip:
    value: 0.569971526277708
gradient_checkpointing:
    value: false
hidden_dim:
    value: 1024
learning_rate:
    value: 0.0068141874775006295
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.15437182393589183
            diversity: 0.0191196870865645
            hand_coarse: 1.5156994471381933
            hand_refined: 1.2804993209609892
            kl: 0.0026456936854185355
            object_position: 0.765554534322183
            object_rotation: 0.7943959166045724
            physics: 0.1634312892597024
            reprojection: 0.8173439138603751
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.15437182393589183
loss_weight_diversity:
    value: 0.0191196870865645
loss_weight_hand_coarse:
    value: 1.5156994471381933
loss_weight_hand_refined:
    value: 1.2804993209609892
loss_weight_kl:
    value: 0.0026456936854185355
loss_weight_object_position:
    value: 0.765554534322183
loss_weight_object_rotation:
    value: 0.7943959166045724
loss_weight_physics:
    value: 0.1634312892597024
loss_weight_reprojection:
    value: 0.8173439138603751
lr_mult_new_encoders:
    value: 0.5682565085730598
lr_mult_pretrained:
    value: 0.007669905812627456
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.2
        freeze_layers: 10
        hidden_dim: 1024
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.36272877696805167
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/2yprir2j
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 1.8095806906888065e-07
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9907507819948704
        grad_clip: 0.569971526277708
        learning_rate: 0.0068141874775006295
        log_freq: 100
        min_lr: 1.8095806906888065e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.5682565085730598
            pretrained: 0.007669905812627456
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.002728033968157077
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.002728033968157077
