_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2041148598651553
aug_joint_noise_std:
    value: 0.005027477093256507
aug_rotation_range:
    value: 15.085726998219853
aug_scale_max:
    value: 1.19186067174804
aug_scale_min:
    value: 0.7795394180652275
aug_translation_std:
    value: 0.08357810918112671
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.4703903408407375
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.2041148598651553
            joint_noise_std: 0.005027477093256507
            rotation_range: 15.085726998219853
            scale_range:
                - 0.7795394180652275
                - 1.19186067174804
            translation_std: 0.08357810918112671
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.1
ema_decay:
    value: 0.996927441194224
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_4ofeccab_20250603_231015
freeze_layers:
    value: 10
grad_clip:
    value: 1.5422956792247078
gradient_checkpointing:
    value: false
hidden_dim:
    value: 512
learning_rate:
    value: 0.003778502899792714
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.3577196703459954
            diversity: 0.0021127675034276557
            hand_coarse: 1.9246743196711036
            hand_refined: 1.0532930599110508
            kl: 0.0004545096000779119
            object_position: 1.4959187767676088
            object_rotation: 0.8908555174497614
            physics: 0.19014356847935565
            reprojection: 0.5464178638783053
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.3577196703459954
loss_weight_diversity:
    value: 0.0021127675034276557
loss_weight_hand_coarse:
    value: 1.9246743196711036
loss_weight_hand_refined:
    value: 1.0532930599110508
loss_weight_kl:
    value: 0.0004545096000779119
loss_weight_object_position:
    value: 1.4959187767676088
loss_weight_object_rotation:
    value: 0.8908555174497614
loss_weight_physics:
    value: 0.19014356847935565
loss_weight_reprojection:
    value: 0.5464178638783053
lr_mult_new_encoders:
    value: 0.4683390548772063
lr_mult_pretrained:
    value: 0.0013579214327693624
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.1
        freeze_layers: 10
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.4703903408407375
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/4ofeccab
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 6.016546297584935e-07
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.996927441194224
        grad_clip: 1.5422956792247078
        learning_rate: 0.003778502899792714
        log_freq: 100
        min_lr: 6.016546297584935e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.4683390548772063
            pretrained: 0.0013579214327693624
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.00015179537113137924
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.00015179537113137924
