_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.13433851558147578
aug_joint_noise_std:
    value: 0.0055916371337500935
aug_rotation_range:
    value: 10.585086765813202
aug_scale_max:
    value: 1.2664225308092916
aug_scale_min:
    value: 0.7939270968675446
aug_translation_std:
    value: 0.05583910126256987
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.579052421527114
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.13433851558147578
            joint_noise_std: 0.0055916371337500935
            rotation_range: 10.585086765813202
            scale_range:
                - 0.7939270968675446
                - 1.2664225308092916
            translation_std: 0.05583910126256987
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.1
ema_decay:
    value: 0.9941460807184032
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_8zfw4qwj_20250603_231221
freeze_layers:
    value: 8
grad_clip:
    value: 0.5370139718107221
gradient_checkpointing:
    value: true
hidden_dim:
    value: 512
learning_rate:
    value: 0.003825768009523742
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.13671865925580462
            diversity: 0.002159103846165012
            hand_coarse: 1.2813654556406382
            hand_refined: 1.1709329976430194
            kl: 0.007189223182370632
            object_position: 1.3869955997292789
            object_rotation: 0.8940641131187266
            physics: 0.17629554152205917
            reprojection: 0.33412097569738086
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.13671865925580462
loss_weight_diversity:
    value: 0.002159103846165012
loss_weight_hand_coarse:
    value: 1.2813654556406382
loss_weight_hand_refined:
    value: 1.1709329976430194
loss_weight_kl:
    value: 0.007189223182370632
loss_weight_object_position:
    value: 1.3869955997292789
loss_weight_object_rotation:
    value: 0.8940641131187266
loss_weight_physics:
    value: 0.17629554152205917
loss_weight_reprojection:
    value: 0.33412097569738086
lr_mult_new_encoders:
    value: 0.7287619340265874
lr_mult_pretrained:
    value: 0.0045106027197685935
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.1
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.579052421527114
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/8zfw4qwj
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 4.461300862635384e-07
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9941460807184032
        grad_clip: 0.5370139718107221
        learning_rate: 0.003825768009523742
        log_freq: 100
        min_lr: 4.461300862635384e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.7287619340265874
            pretrained: 0.0045106027197685935
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0002000157086439601
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0002000157086439601
