_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2243158419722358
aug_joint_noise_std:
    value: 0.004702267567070829
aug_rotation_range:
    value: 12.038978293738973
aug_scale_max:
    value: 1.2581937225010833
aug_scale_min:
    value: 0.7930900068073665
aug_translation_std:
    value: 0.02100359041551222
batch_size:
    value: 256
diversity_margin:
    value: 0.0069266685342013225
dropout:
    value: 0.3
fingertip_weight:
    value: 1.861392215404659
loss_weight_contact:
    value: 0.4869461578493837
loss_weight_diversity:
    value: 0.04866880211674292
loss_weight_hand_coarse:
    value: 0.9400985225622004
loss_weight_hand_refined:
    value: 1.0763452875470878
loss_weight_object_position:
    value: 1.0477027184828662
loss_weight_object_rotation:
    value: 0.5119823254798943
loss_weight_physics:
    value: 0.09456322267970872
loss_weight_reprojection:
    value: 0.6995082476175166
per_joint_weighting:
    value: true
scheduler_type:
    value: exponential
