_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.17512835048365566
aug_joint_noise_std:
    value: 0.0023872760859695473
aug_rotation_range:
    value: 12.246648798697397
aug_scale_max:
    value: 1.1110242007187314
aug_scale_min:
    value: 0.8838377507465349
aug_translation_std:
    value: 0.08324277674109128
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.5482356865893259
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.17512835048365566
            joint_noise_std: 0.0023872760859695473
            rotation_range: 12.246648798697397
            scale_range:
                - 0.8838377507465349
                - 1.1110242007187314
            translation_std: 0.08324277674109128
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.998252820349548
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_fdtnx9mn_20250604_001636
freeze_layers:
    value: 8
grad_clip:
    value: 0.7689374642564741
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 1.4865471820213486e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.3500171898818625
            diversity: 0.07375987008213414
            hand_coarse: 1.7634275427322246
            hand_refined: 2.2388161918165768
            kl: 0.0006043947641310727
            object_position: 0.5915020093709498
            object_rotation: 0.7479057951255967
            physics: 0.18973111279964175
            reprojection: 0.915447150381937
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.3500171898818625
loss_weight_diversity:
    value: 0.07375987008213414
loss_weight_hand_coarse:
    value: 1.7634275427322246
loss_weight_hand_refined:
    value: 2.2388161918165768
loss_weight_kl:
    value: 0.0006043947641310727
loss_weight_object_position:
    value: 0.5915020093709498
loss_weight_object_rotation:
    value: 0.7479057951255967
loss_weight_physics:
    value: 0.18973111279964175
loss_weight_reprojection:
    value: 0.915447150381937
lr_mult_new_encoders:
    value: 0.36434140574918367
lr_mult_pretrained:
    value: 0.01883807963573532
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.3
        freeze_layers: 8
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.5482356865893259
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/fdtnx9mn
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 3.929651487725069e-06
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.998252820349548
        grad_clip: 0.7689374642564741
        learning_rate: 1.4865471820213486e-05
        log_freq: 100
        min_lr: 3.929651487725069e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.36434140574918367
            pretrained: 0.01883807963573532
        num_epochs: 20
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.00048670245786723457
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.00048670245786723457
