_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.15821678462446614
aug_joint_noise_std:
    value: 0.005184458914697496
aug_rotation_range:
    value: 10.981201642569149
aug_scale_max:
    value: 1.150491120141652
aug_scale_min:
    value: 0.811219901259411
aug_translation_std:
    value: 0.057908239866384936
batch_size:
    value: 32
diversity_margin:
    value: 0.019043208025791063
dropout:
    value: 0.25
fingertip_weight:
    value: 1.2140457775884883
loss_weight_contact:
    value: 0.42437293822461986
loss_weight_diversity:
    value: 0.018276993213881737
loss_weight_hand_coarse:
    value: 0.948812525328656
loss_weight_hand_refined:
    value: 1.015557612232345
loss_weight_object_position:
    value: 0.8480554525983992
loss_weight_object_rotation:
    value: 0.46980433036257174
loss_weight_physics:
    value: 0.07801855016510321
loss_weight_reprojection:
    value: 0.4632224287029423
per_joint_weighting:
    value: false
scheduler_type:
    value: exponential
