_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2757223154913153
aug_joint_noise_std:
    value: 0.009665840796259748
aug_rotation_range:
    value: 22.04301640638363
aug_scale_max:
    value: 1.2050909261116585
aug_scale_min:
    value: 0.733743467798308
aug_translation_std:
    value: 0.04822374536091338
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.49627851579336457
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.2757223154913153
            joint_noise_std: 0.009665840796259748
            rotation_range: 22.04301640638363
            scale_range:
                - 0.733743467798308
                - 1.2050909261116585
            translation_std: 0.04822374536091338
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9982359673031418
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_d1zudsov_20250603_231125
freeze_layers:
    value: 8
grad_clip:
    value: 1.595398833239987
gradient_checkpointing:
    value: false
hidden_dim:
    value: 512
learning_rate:
    value: 0.0001617983784575258
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.3031122051276586
            diversity: 0.044652134855590886
            hand_coarse: 1.1968883867241065
            hand_refined: 1.4016115402522744
            kl: 0.0001896040724958328
            object_position: 0.860252472078523
            object_rotation: 0.6514520576603717
            physics: 0.11125588669820596
            reprojection: 0.5498144431302388
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.3031122051276586
loss_weight_diversity:
    value: 0.044652134855590886
loss_weight_hand_coarse:
    value: 1.1968883867241065
loss_weight_hand_refined:
    value: 1.4016115402522744
loss_weight_kl:
    value: 0.0001896040724958328
loss_weight_object_position:
    value: 0.860252472078523
loss_weight_object_rotation:
    value: 0.6514520576603717
loss_weight_physics:
    value: 0.11125588669820596
loss_weight_reprojection:
    value: 0.5498144431302388
lr_mult_new_encoders:
    value: 0.6296559820955432
lr_mult_pretrained:
    value: 0.009713015436366558
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.3
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.49627851579336457
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/d1zudsov
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 5.99859990039968e-06
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.9982359673031418
        grad_clip: 1.595398833239987
        learning_rate: 0.0001617983784575258
        log_freq: 100
        min_lr: 5.99859990039968e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.6296559820955432
            pretrained: 0.009713015436366558
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.014837476602881972
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.014837476602881972
