_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.22495246580195027
aug_joint_noise_std:
    value: 0.005107647234493206
aug_rotation_range:
    value: 15.064533654791372
aug_scale_max:
    value: 1.2959778901568737
aug_scale_min:
    value: 0.8207290171158513
aug_translation_std:
    value: 0.09238057640580465
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.6733388660351018
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.22495246580195027
            joint_noise_std: 0.005107647234493206
            rotation_range: 15.064533654791372
            scale_range:
                - 0.8207290171158513
                - 1.2959778901568737
            translation_std: 0.09238057640580465
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.9934789014247064
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_xljos3zf_20250603_231004
freeze_layers:
    value: 12
grad_clip:
    value: 0.6138186040459885
gradient_checkpointing:
    value: false
hidden_dim:
    value: 1024
learning_rate:
    value: 0.000593128493301739
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.3234685798425708
            diversity: 0.03570512140805411
            hand_coarse: 0.731430209271603
            hand_refined: 1.3581228807677024
            kl: 0.0003029988156228047
            object_position: 1.37912195370744
            object_rotation: 0.5745381962094465
            physics: 0.1664128332685657
            reprojection: 0.4676975327536469
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.3234685798425708
loss_weight_diversity:
    value: 0.03570512140805411
loss_weight_hand_coarse:
    value: 0.731430209271603
loss_weight_hand_refined:
    value: 1.3581228807677024
loss_weight_kl:
    value: 0.0003029988156228047
loss_weight_object_position:
    value: 1.37912195370744
loss_weight_object_rotation:
    value: 0.5745381962094465
loss_weight_physics:
    value: 0.1664128332685657
loss_weight_reprojection:
    value: 0.4676975327536469
lr_mult_new_encoders:
    value: 0.6750464531380587
lr_mult_pretrained:
    value: 0.09088131449778204
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.2
        freeze_layers: 12
        hidden_dim: 1024
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.6733388660351018
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/xljos3zf
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 1.821410898650416e-07
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9934789014247064
        grad_clip: 0.6138186040459885
        learning_rate: 0.000593128493301739
        log_freq: 100
        min_lr: 1.821410898650416e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.6750464531380587
            pretrained: 0.09088131449778204
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0011787108820659911
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0011787108820659911
