_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.24454528743473136
aug_joint_noise_std:
    value: 0.007932944628698639
aug_rotation_range:
    value: 5.71360886499428
aug_scale_max:
    value: 1.2433753984755511
aug_scale_min:
    value: 0.8396469272856542
aug_translation_std:
    value: 0.02581771617624308
batch_size:
    value: 32
diversity_margin:
    value: 0.011440928918859512
dropout:
    value: 0.25
fingertip_weight:
    value: 1.5299005787552664
loss_weight_contact:
    value: 0.4583407817395416
loss_weight_diversity:
    value: 0.005209688871113964
loss_weight_hand_coarse:
    value: 0.8376674797727754
loss_weight_hand_refined:
    value: 1.4443432730678134
loss_weight_object_position:
    value: 1.1865868505031134
loss_weight_object_rotation:
    value: 0.386328073309788
loss_weight_physics:
    value: 0.059720698353751926
loss_weight_reprojection:
    value: 0.6675281096059253
per_joint_weighting:
    value: true
scheduler_type:
    value: cosine
