_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.1383660633207709
aug_joint_noise_std:
    value: 0.004873040809796789
aug_rotation_range:
    value: 18.22618113812288
aug_scale_max:
    value: 1.2804305315281326
aug_scale_min:
    value: 0.8899825624072685
aug_translation_std:
    value: 0.08019293772012265
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.3365672718953854
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.1383660633207709
            joint_noise_std: 0.004873040809796789
            rotation_range: 18.22618113812288
            scale_range:
                - 0.8899825624072685
                - 1.2804305315281326
            translation_std: 0.08019293772012265
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.9942935133797592
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_zigketid_20250603_231020
freeze_layers:
    value: 8
grad_clip:
    value: 1.8037620265740857
gradient_checkpointing:
    value: true
hidden_dim:
    value: 768
learning_rate:
    value: 3.412950049801813e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.44921093949018864
            diversity: 0.001210846423056592
            hand_coarse: 1.1567147951114278
            hand_refined: 1.5825890007642214
            kl: 0.002031804714858926
            object_position: 0.7774102465954869
            object_rotation: 0.5364077575767708
            physics: 0.1896051070017528
            reprojection: 0.6820360451587044
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.44921093949018864
loss_weight_diversity:
    value: 0.001210846423056592
loss_weight_hand_coarse:
    value: 1.1567147951114278
loss_weight_hand_refined:
    value: 1.5825890007642214
loss_weight_kl:
    value: 0.002031804714858926
loss_weight_object_position:
    value: 0.7774102465954869
loss_weight_object_rotation:
    value: 0.5364077575767708
loss_weight_physics:
    value: 0.1896051070017528
loss_weight_reprojection:
    value: 0.6820360451587044
lr_mult_new_encoders:
    value: 0.7229858769628158
lr_mult_pretrained:
    value: 0.03621208862917651
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.2
        freeze_layers: 8
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.3365672718953854
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/zigketid
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 9.75233776769956e-07
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9942935133797592
        grad_clip: 1.8037620265740857
        learning_rate: 3.412950049801813e-05
        log_freq: 100
        min_lr: 9.75233776769956e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.7229858769628158
            pretrained: 0.03621208862917651
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0005951317853007246
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0005951317853007246
