_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2819099318088629
aug_joint_noise_std:
    value: 0.0031771306653864805
aug_rotation_range:
    value: 11.634493333174625
aug_scale_max:
    value: 1.1438781605668722
aug_scale_min:
    value: 0.7393216251014889
aug_translation_std:
    value: 0.07725373312542694
batch_size:
    value: 256
diversity_margin:
    value: 0.01250515381976098
dropout:
    value: 0.25
fingertip_weight:
    value: 1.6925361140982702
loss_weight_contact:
    value: 0.4219063151668758
loss_weight_diversity:
    value: 0.005275453667342303
loss_weight_hand_coarse:
    value: 0.9406857289868484
loss_weight_hand_refined:
    value: 1.2727904574284077
loss_weight_object_position:
    value: 0.8841540818375416
loss_weight_object_rotation:
    value: 0.5561457368385831
loss_weight_physics:
    value: 0.12837855813364585
loss_weight_reprojection:
    value: 0.4820135305418606
per_joint_weighting:
    value: true
scheduler_type:
    value: step
