_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.15810085410439417
aug_joint_noise_std:
    value: 0.004603432545668355
aug_rotation_range:
    value: 11.088077984119147
aug_scale_max:
    value: 1.187745857597685
aug_scale_min:
    value: 0.7231426161986108
aug_translation_std:
    value: 0.043651501626426545
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.4672839369549343
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.15810085410439417
            joint_noise_std: 0.004603432545668355
            rotation_range: 11.088077984119147
            scale_range:
                - 0.7231426161986108
                - 1.187745857597685
            translation_std: 0.043651501626426545
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.9902477227340504
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_klqo71dc_20250603_230936
freeze_layers:
    value: 10
grad_clip:
    value: 1.5616955549650513
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 0.0002782631733416597
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.4861177231472259
            diversity: 0.05444477616694396
            hand_coarse: 1.0512830505939132
            hand_refined: 1.905482225682299
            kl: 0.0035713987486502307
            object_position: 0.7550784752585457
            object_rotation: 0.759574429377186
            physics: 0.16770151096293848
            reprojection: 0.7403310922979642
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.4861177231472259
loss_weight_diversity:
    value: 0.05444477616694396
loss_weight_hand_coarse:
    value: 1.0512830505939132
loss_weight_hand_refined:
    value: 1.905482225682299
loss_weight_kl:
    value: 0.0035713987486502307
loss_weight_object_position:
    value: 0.7550784752585457
loss_weight_object_rotation:
    value: 0.759574429377186
loss_weight_physics:
    value: 0.16770151096293848
loss_weight_reprojection:
    value: 0.7403310922979642
lr_mult_new_encoders:
    value: 0.7193816851152369
lr_mult_pretrained:
    value: 0.0204532370297449
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.2
        freeze_layers: 10
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.4672839369549343
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/klqo71dc
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 8.850820565239353e-06
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9902477227340504
        grad_clip: 1.5616955549650513
        learning_rate: 0.0002782631733416597
        log_freq: 100
        min_lr: 8.850820565239353e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.7193816851152369
            pretrained: 0.0204532370297449
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.022112605674937252
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.022112605674937252
