_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2151638586416877
aug_joint_noise_std:
    value: 0.008336425755834325
aug_rotation_range:
    value: 13.298444260827118
aug_scale_max:
    value: 1.13682328937637
aug_scale_min:
    value: 0.7409737362909905
aug_translation_std:
    value: 0.030802414238023577
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.4543595175995157
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.2151638586416877
            joint_noise_std: 0.008336425755834325
            rotation_range: 13.298444260827118
            scale_range:
                - 0.7409737362909905
                - 1.13682328937637
            translation_std: 0.030802414238023577
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.1
ema_decay:
    value: 0.9927698533483792
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_2g50w6bu_20250603_231321
freeze_layers:
    value: 8
grad_clip:
    value: 0.5290885805230384
gradient_checkpointing:
    value: false
hidden_dim:
    value: 512
learning_rate:
    value: 0.00285844013701737
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.17220101128718396
            diversity: 0.07111127311821648
            hand_coarse: 1.625579409580033
            hand_refined: 1.7601081100770295
            kl: 0.00031154189873893866
            object_position: 1.367784644122905
            object_rotation: 0.4231204834047322
            physics: 0.05253132433871929
            reprojection: 0.379314168254045
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.17220101128718396
loss_weight_diversity:
    value: 0.07111127311821648
loss_weight_hand_coarse:
    value: 1.625579409580033
loss_weight_hand_refined:
    value: 1.7601081100770295
loss_weight_kl:
    value: 0.00031154189873893866
loss_weight_object_position:
    value: 1.367784644122905
loss_weight_object_rotation:
    value: 0.4231204834047322
loss_weight_physics:
    value: 0.05253132433871929
loss_weight_reprojection:
    value: 0.379314168254045
lr_mult_new_encoders:
    value: 0.39620734999899454
lr_mult_pretrained:
    value: 0.010319862781656136
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.1
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.4543595175995157
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/2g50w6bu
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 3.471906292666669e-07
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9927698533483792
        grad_clip: 0.5290885805230384
        learning_rate: 0.00285844013701737
        log_freq: 100
        min_lr: 3.471906292666669e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.39620734999899454
            pretrained: 0.010319862781656136
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.00021094062483332336
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.00021094062483332336
