_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2990024778490896
aug_joint_noise_std:
    value: 0.009923877797330938
aug_rotation_range:
    value: 29.594804194009154
aug_scale_max:
    value: 1.1481761390172285
aug_scale_min:
    value: 0.8115992592790595
aug_translation_std:
    value: 0.04662229238879877
batch_size:
    value: 16
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.5811584632521548
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.2990024778490896
            joint_noise_std: 0.009923877797330938
            rotation_range: 29.594804194009154
            scale_range:
                - 0.8115992592790595
                - 1.1481761390172285
            translation_std: 0.04662229238879877
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9906534187144208
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_u7pvmscc_20250603_231131
freeze_layers:
    value: 8
grad_clip:
    value: 1.113413109982212
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 2.8255873985078566e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.3372152015710273
            diversity: 0.08575377751760177
            hand_coarse: 1.0330168201485184
            hand_refined: 1.076747396263698
            kl: 0.0005046233644835954
            object_position: 1.7735125078869358
            object_rotation: 0.5846965217737357
            physics: 0.10238731384084591
            reprojection: 0.7562764489951788
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.3372152015710273
loss_weight_diversity:
    value: 0.08575377751760177
loss_weight_hand_coarse:
    value: 1.0330168201485184
loss_weight_hand_refined:
    value: 1.076747396263698
loss_weight_kl:
    value: 0.0005046233644835954
loss_weight_object_position:
    value: 1.7735125078869358
loss_weight_object_rotation:
    value: 0.5846965217737357
loss_weight_physics:
    value: 0.10238731384084591
loss_weight_reprojection:
    value: 0.7562764489951788
lr_mult_new_encoders:
    value: 0.6172073924745378
lr_mult_pretrained:
    value: 0.026076694335218024
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.3
        freeze_layers: 8
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.5811584632521548
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/u7pvmscc
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 1.1913011911375631e-06
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 16
        ema_decay: 0.9906534187144208
        grad_clip: 1.113413109982212
        learning_rate: 2.8255873985078566e-05
        log_freq: 100
        min_lr: 1.1913011911375631e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.6172073924745378
            pretrained: 0.026076694335218024
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0012801738590790537
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0012801738590790537
