_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.10962495493999136
aug_joint_noise_std:
    value: 0.007284278044543747
aug_rotation_range:
    value: 10.848093914434196
aug_scale_max:
    value: 1.2848093335952857
aug_scale_min:
    value: 0.7985654770914782
aug_translation_std:
    value: 0.07799315869086339
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.4038981326704319
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.10962495493999136
            joint_noise_std: 0.007284278044543747
            rotation_range: 10.848093914434196
            scale_range:
                - 0.7985654770914782
                - 1.2848093335952857
            translation_std: 0.07799315869086339
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.997045886299862
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_j2s78ys8_20250603_231349
freeze_layers:
    value: 8
grad_clip:
    value: 1.8917556581785944
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 0.0024616501466053547
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.1411538744330314
            diversity: 0.0312221675932439
            hand_coarse: 1.857647299298849
            hand_refined: 1.672428950993953
            kl: 0.0012628820929355723
            object_position: 1.0043786342514054
            object_rotation: 0.9829095382931444
            physics: 0.1836729796449296
            reprojection: 0.912609347812591
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.1411538744330314
loss_weight_diversity:
    value: 0.0312221675932439
loss_weight_hand_coarse:
    value: 1.857647299298849
loss_weight_hand_refined:
    value: 1.672428950993953
loss_weight_kl:
    value: 0.0012628820929355723
loss_weight_object_position:
    value: 1.0043786342514054
loss_weight_object_rotation:
    value: 0.9829095382931444
loss_weight_physics:
    value: 0.1836729796449296
loss_weight_reprojection:
    value: 0.912609347812591
lr_mult_new_encoders:
    value: 0.6745969331960726
lr_mult_pretrained:
    value: 0.008369245889066566
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.2
        freeze_layers: 8
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.4038981326704319
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/j2s78ys8
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 6.2785127123743645e-06
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.997045886299862
        grad_clip: 1.8917556581785944
        learning_rate: 0.0024616501466053547
        log_freq: 100
        min_lr: 6.2785127123743645e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.6745969331960726
            pretrained: 0.008369245889066566
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0014150898056509331
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0014150898056509331
