_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2278527973729676
aug_joint_noise_std:
    value: 0.009761024477961008
aug_rotation_range:
    value: 24.404407964959837
aug_scale_max:
    value: 1.2862648057670676
aug_scale_min:
    value: 0.7097453595134082
aug_translation_std:
    value: 0.07445022141194167
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.34549464787826284
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.2278527973729676
            joint_noise_std: 0.009761024477961008
            rotation_range: 24.404407964959837
            scale_range:
                - 0.7097453595134082
                - 1.2862648057670676
            translation_std: 0.07445022141194167
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.9983588766817332
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_kc30e2kh_20250603_231114
freeze_layers:
    value: 8
grad_clip:
    value: 1.309108330975514
gradient_checkpointing:
    value: true
hidden_dim:
    value: 512
learning_rate:
    value: 1.6518980524559546e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.44904083473982814
            diversity: 0.028979301225397575
            hand_coarse: 1.403413746819131
            hand_refined: 2.3286155070681476
            kl: 0.0007204852964291175
            object_position: 0.7419216213114554
            object_rotation: 0.4197780677918968
            physics: 0.11270843960392724
            reprojection: 0.38784974682159334
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.44904083473982814
loss_weight_diversity:
    value: 0.028979301225397575
loss_weight_hand_coarse:
    value: 1.403413746819131
loss_weight_hand_refined:
    value: 2.3286155070681476
loss_weight_kl:
    value: 0.0007204852964291175
loss_weight_object_position:
    value: 0.7419216213114554
loss_weight_object_rotation:
    value: 0.4197780677918968
loss_weight_physics:
    value: 0.11270843960392724
loss_weight_reprojection:
    value: 0.38784974682159334
lr_mult_new_encoders:
    value: 0.4329866966152468
lr_mult_pretrained:
    value: 0.004026364381572944
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.2
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.34549464787826284
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/kc30e2kh
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 6.145530973071265e-06
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.9983588766817332
        grad_clip: 1.309108330975514
        learning_rate: 1.6518980524559546e-05
        log_freq: 100
        min_lr: 6.145530973071265e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.4329866966152468
            pretrained: 0.004026364381572944
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.000740332064910551
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.000740332064910551
