_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.12672901733760675
aug_joint_noise_std:
    value: 0.007193260637694643
aug_rotation_range:
    value: 6.628984156972136
aug_scale_max:
    value: 1.141491857908568
aug_scale_min:
    value: 0.763721096146292
aug_translation_std:
    value: 0.04420020041596818
batch_size:
    value: 64
diversity_margin:
    value: 0.015935998751044223
dropout:
    value: 0.15
fingertip_weight:
    value: 1.2928481824627232
loss_weight_contact:
    value: 0.3580475031070855
loss_weight_diversity:
    value: 0.024383808756130564
loss_weight_hand_coarse:
    value: 0.9875224109515356
loss_weight_hand_refined:
    value: 1.1678958910650228
loss_weight_object_position:
    value: 1.077452397643558
loss_weight_object_rotation:
    value: 0.49291371329188305
loss_weight_physics:
    value: 0.16178025438023036
loss_weight_reprojection:
    value: 0.3220367553222794
per_joint_weighting:
    value: true
scheduler_type:
    value: step
