_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2149506434684888
aug_joint_noise_std:
    value: 0.0032914299816099
aug_rotation_range:
    value: 15.933822495493482
aug_scale_max:
    value: 1.1388105490879274
aug_scale_min:
    value: 0.8534150202477693
aug_translation_std:
    value: 0.0839749410778938
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.4128298226556717
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.2149506434684888
            joint_noise_std: 0.0032914299816099
            rotation_range: 15.933822495493482
            scale_range:
                - 0.8534150202477693
                - 1.1388105490879274
            translation_std: 0.0839749410778938
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.1
ema_decay:
    value: 0.9949514841908388
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_tey8dniv_20250604_000109
freeze_layers:
    value: 12
grad_clip:
    value: 0.7120138198547212
gradient_checkpointing:
    value: true
hidden_dim:
    value: 768
learning_rate:
    value: 0.0003303992064735239
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.15686208195080745
            diversity: 0.0025989555170165975
            hand_coarse: 1.4502599365207476
            hand_refined: 1.8427541869626172
            kl: 0.001582896585253114
            object_position: 1.024948228891714
            object_rotation: 0.4386283400350265
            physics: 0.10059444328417884
            reprojection: 0.7041952750106959
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.15686208195080745
loss_weight_diversity:
    value: 0.0025989555170165975
loss_weight_hand_coarse:
    value: 1.4502599365207476
loss_weight_hand_refined:
    value: 1.8427541869626172
loss_weight_kl:
    value: 0.001582896585253114
loss_weight_object_position:
    value: 1.024948228891714
loss_weight_object_rotation:
    value: 0.4386283400350265
loss_weight_physics:
    value: 0.10059444328417884
loss_weight_reprojection:
    value: 0.7041952750106959
lr_mult_new_encoders:
    value: 0.5035248187210781
lr_mult_pretrained:
    value: 0.004404251355476028
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.1
        freeze_layers: 12
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.4128298226556717
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/tey8dniv
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 1.995486566110701e-07
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.9949514841908388
        grad_clip: 0.7120138198547212
        learning_rate: 0.0003303992064735239
        log_freq: 100
        min_lr: 1.995486566110701e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.5035248187210781
            pretrained: 0.004404251355476028
        num_epochs: 20
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0008110878519680234
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0008110878519680234
