_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2847508347155796
aug_joint_noise_std:
    value: 0.002257140343437012
aug_rotation_range:
    value: 18.290491961092417
aug_scale_max:
    value: 1.1120320351809658
aug_scale_min:
    value: 0.7892585657293049
aug_translation_std:
    value: 0.08575630024361429
batch_size:
    value: 16
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.37811482195835416
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.2847508347155796
            joint_noise_std: 0.002257140343437012
            rotation_range: 18.290491961092417
            scale_range:
                - 0.7892585657293049
                - 1.1120320351809658
            translation_std: 0.08575630024361429
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9917428688492992
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_tmgl828p_20250603_231305
freeze_layers:
    value: 8
grad_clip:
    value: 0.8171395399410368
gradient_checkpointing:
    value: true
hidden_dim:
    value: 512
learning_rate:
    value: 1.5965402796920205e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.3164271768608329
            diversity: 0.058505277763285984
            hand_coarse: 0.9031634478409124
            hand_refined: 1.8079065392582752
            kl: 0.0017203225893819012
            object_position: 1.4941941349811598
            object_rotation: 0.6196755562812841
            physics: 0.10485222097924776
            reprojection: 0.5033830766773719
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.3164271768608329
loss_weight_diversity:
    value: 0.058505277763285984
loss_weight_hand_coarse:
    value: 0.9031634478409124
loss_weight_hand_refined:
    value: 1.8079065392582752
loss_weight_kl:
    value: 0.0017203225893819012
loss_weight_object_position:
    value: 1.4941941349811598
loss_weight_object_rotation:
    value: 0.6196755562812841
loss_weight_physics:
    value: 0.10485222097924776
loss_weight_reprojection:
    value: 0.5033830766773719
lr_mult_new_encoders:
    value: 0.6140354164879576
lr_mult_pretrained:
    value: 0.001804450504274231
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.3
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.37811482195835416
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/tmgl828p
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 5.897447792781725e-06
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 16
        ema_decay: 0.9917428688492992
        grad_clip: 0.8171395399410368
        learning_rate: 1.5965402796920205e-05
        log_freq: 100
        min_lr: 5.897447792781725e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.6140354164879576
            pretrained: 0.001804450504274231
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.05082062607834073
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.05082062607834073
