_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.1680787753446761
aug_joint_noise_std:
    value: 0.007606157930007194
aug_rotation_range:
    value: 7.123497244822974
aug_scale_max:
    value: 1.1417004615689508
aug_scale_min:
    value: 0.758904864686229
aug_translation_std:
    value: 0.036082238372322085
batch_size:
    value: 32
diversity_margin:
    value: 0.017923163535487664
dropout:
    value: 0.15
fingertip_weight:
    value: 1.3693630614169268
loss_weight_contact:
    value: 0.35933105625469663
loss_weight_diversity:
    value: 0.005984291555355641
loss_weight_hand_coarse:
    value: 1.1325970922650106
loss_weight_hand_refined:
    value: 1.18923514356987
loss_weight_object_position:
    value: 0.8218849761978071
loss_weight_object_rotation:
    value: 0.46322918880595465
loss_weight_physics:
    value: 0.08561881455729764
loss_weight_reprojection:
    value: 0.5528677623688192
per_joint_weighting:
    value: false
scheduler_type:
    value: step
