_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2124895523942364
aug_joint_noise_std:
    value: 0.007820596678561248
aug_rotation_range:
    value: 17.35732155028538
aug_scale_max:
    value: 1.110137090123293
aug_scale_min:
    value: 0.8492195119656026
aug_translation_std:
    value: 0.03548236950735257
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.36878220170576714
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.2124895523942364
            joint_noise_std: 0.007820596678561248
            rotation_range: 17.35732155028538
            scale_range:
                - 0.8492195119656026
                - 1.110137090123293
            translation_std: 0.03548236950735257
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.1
ema_decay:
    value: 0.993012310407886
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_basq04rr_20250604_003909
freeze_layers:
    value: 10
grad_clip:
    value: 1.3987804898659613
gradient_checkpointing:
    value: true
hidden_dim:
    value: 768
learning_rate:
    value: 3.1701959865658684e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.36552609534373326
            diversity: 0.009241976540013123
            hand_coarse: 1.586435525132895
            hand_refined: 1.2113324025669776
            kl: 0.0017120240009589473
            object_position: 1.7579038454149605
            object_rotation: 0.7645827077910108
            physics: 0.08795119041020175
            reprojection: 0.7767471821996061
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.36552609534373326
loss_weight_diversity:
    value: 0.009241976540013123
loss_weight_hand_coarse:
    value: 1.586435525132895
loss_weight_hand_refined:
    value: 1.2113324025669776
loss_weight_kl:
    value: 0.0017120240009589473
loss_weight_object_position:
    value: 1.7579038454149605
loss_weight_object_rotation:
    value: 0.7645827077910108
loss_weight_physics:
    value: 0.08795119041020175
loss_weight_reprojection:
    value: 0.7767471821996061
lr_mult_new_encoders:
    value: 0.5901631110146649
lr_mult_pretrained:
    value: 0.027854695532812685
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.1
        freeze_layers: 10
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.36878220170576714
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/basq04rr
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 7.332562076297543e-07
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.993012310407886
        grad_clip: 1.3987804898659613
        learning_rate: 3.1701959865658684e-05
        log_freq: 100
        min_lr: 7.332562076297543e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.5901631110146649
            pretrained: 0.027854695532812685
        num_epochs: 20
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0003245170535792817
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0003245170535792817
