_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.13848035583098073
aug_joint_noise_std:
    value: 0.00456626380919002
aug_rotation_range:
    value: 27.76406679729213
aug_scale_max:
    value: 1.2592210901079652
aug_scale_min:
    value: 0.7582653034732221
aug_translation_std:
    value: 0.07521229455652592
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.6537858239046566
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.13848035583098073
            joint_noise_std: 0.00456626380919002
            rotation_range: 27.76406679729213
            scale_range:
                - 0.7582653034732221
                - 1.2592210901079652
            translation_std: 0.07521229455652592
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.994816175748668
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_p7tuie3w_20250603_231354
freeze_layers:
    value: 12
grad_clip:
    value: 1.3597381976978171
gradient_checkpointing:
    value: true
hidden_dim:
    value: 512
learning_rate:
    value: 0.00039547231771417334
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.15497072238508897
            diversity: 0.002819928225947235
            hand_coarse: 1.5646384440747854
            hand_refined: 1.5587011175941854
            kl: 0.0003386986323084468
            object_position: 1.082074136664019
            object_rotation: 0.8809189887385651
            physics: 0.122293540549803
            reprojection: 0.5046206316850825
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.15497072238508897
loss_weight_diversity:
    value: 0.002819928225947235
loss_weight_hand_coarse:
    value: 1.5646384440747854
loss_weight_hand_refined:
    value: 1.5587011175941854
loss_weight_kl:
    value: 0.0003386986323084468
loss_weight_object_position:
    value: 1.082074136664019
loss_weight_object_rotation:
    value: 0.8809189887385651
loss_weight_physics:
    value: 0.122293540549803
loss_weight_reprojection:
    value: 0.5046206316850825
lr_mult_new_encoders:
    value: 0.3311485683681513
lr_mult_pretrained:
    value: 0.013113460456338488
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.2
        freeze_layers: 12
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.6537858239046566
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/p7tuie3w
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 3.700710246640632e-06
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.994816175748668
        grad_clip: 1.3597381976978171
        learning_rate: 0.00039547231771417334
        log_freq: 100
        min_lr: 3.700710246640632e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.3311485683681513
            pretrained: 0.013113460456338488
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.00017309797807137526
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.00017309797807137526
