_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 1
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.252811498362129
aug_joint_noise_std:
    value: 0.005845042607027987
aug_rotation_range:
    value: 8.196033817484096
aug_scale_max:
    value: 1.17457148369831
aug_scale_min:
    value: 0.8968418285007773
aug_translation_std:
    value: 0.03871014363638063
batch_size:
    value: 32
diversity_margin:
    value: 0.018158201024824672
dropout:
    value: 0.3
fingertip_weight:
    value: 1.51136983309714
loss_weight_contact:
    value: 0.3702389758601501
loss_weight_diversity:
    value: 0.025457487190665744
loss_weight_hand_coarse:
    value: 1.1575365448892314
loss_weight_hand_refined:
    value: 1.3692677988047055
loss_weight_object_position:
    value: 1.153359724517229
loss_weight_object_rotation:
    value: 0.5737631208294376
loss_weight_physics:
    value: 0.18158911700618596
loss_weight_reprojection:
    value: 0.5173296475532774
per_joint_weighting:
    value: true
scheduler_type:
    value: exponential
