_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2692327014031646
aug_joint_noise_std:
    value: 0.004152547882243167
aug_rotation_range:
    value: 21.40235840260239
aug_scale_max:
    value: 1.281628691336224
aug_scale_min:
    value: 0.7624559361614996
aug_translation_std:
    value: 0.022498565839146244
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.4730259152550106
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.2692327014031646
            joint_noise_std: 0.004152547882243167
            rotation_range: 21.40235840260239
            scale_range:
                - 0.7624559361614996
                - 1.281628691336224
            translation_std: 0.022498565839146244
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.1
ema_decay:
    value: 0.9925994267619602
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_kzmvufm2_20250603_230930
freeze_layers:
    value: 8
grad_clip:
    value: 1.72482327045533
gradient_checkpointing:
    value: true
hidden_dim:
    value: 768
learning_rate:
    value: 0.00899009336870645
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.16524741487890418
            diversity: 0.05151068546722829
            hand_coarse: 1.3835528799823105
            hand_refined: 2.1674138651802917
            kl: 0.00023201511341090436
            object_position: 1.5749275041448922
            object_rotation: 0.6197879171644507
            physics: 0.1816268370641568
            reprojection: 0.5710792150748276
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.16524741487890418
loss_weight_diversity:
    value: 0.05151068546722829
loss_weight_hand_coarse:
    value: 1.3835528799823105
loss_weight_hand_refined:
    value: 2.1674138651802917
loss_weight_kl:
    value: 0.00023201511341090436
loss_weight_object_position:
    value: 1.5749275041448922
loss_weight_object_rotation:
    value: 0.6197879171644507
loss_weight_physics:
    value: 0.1816268370641568
loss_weight_reprojection:
    value: 0.5710792150748276
lr_mult_new_encoders:
    value: 0.3958715475838685
lr_mult_pretrained:
    value: 0.018038868019609845
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.1
        freeze_layers: 8
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.4730259152550106
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/kzmvufm2
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 1.7279071490980245e-07
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.9925994267619602
        grad_clip: 1.72482327045533
        learning_rate: 0.00899009336870645
        log_freq: 100
        min_lr: 1.7279071490980245e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.3958715475838685
            pretrained: 0.018038868019609845
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0019889878917130283
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0019889878917130283
