_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.13122412982596054
aug_joint_noise_std:
    value: 0.004943345463038127
aug_rotation_range:
    value: 11.058580838890771
aug_scale_max:
    value: 1.217345801622534
aug_scale_min:
    value: 0.795127657940771
aug_translation_std:
    value: 0.02896419682527384
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.4104395047795899
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.13122412982596054
            joint_noise_std: 0.004943345463038127
            rotation_range: 11.058580838890771
            scale_range:
                - 0.795127657940771
                - 1.217345801622534
            translation_std: 0.02896419682527384
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9927571162692338
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_xb2jzg0p_20250603_231042
freeze_layers:
    value: 10
grad_clip:
    value: 1.4265774065857295
gradient_checkpointing:
    value: true
hidden_dim:
    value: 512
learning_rate:
    value: 0.00037199851654233274
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.2827738299626641
            diversity: 0.003938743678710862
            hand_coarse: 0.8532658406322264
            hand_refined: 2.1329257488151296
            kl: 0.002300578859057191
            object_position: 1.4342064544031827
            object_rotation: 0.2802421522155064
            physics: 0.13747398897477606
            reprojection: 0.28159260868272207
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.2827738299626641
loss_weight_diversity:
    value: 0.003938743678710862
loss_weight_hand_coarse:
    value: 0.8532658406322264
loss_weight_hand_refined:
    value: 2.1329257488151296
loss_weight_kl:
    value: 0.002300578859057191
loss_weight_object_position:
    value: 1.4342064544031827
loss_weight_object_rotation:
    value: 0.2802421522155064
loss_weight_physics:
    value: 0.13747398897477606
loss_weight_reprojection:
    value: 0.28159260868272207
lr_mult_new_encoders:
    value: 0.7457103064325055
lr_mult_pretrained:
    value: 0.005200413604068712
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.3
        freeze_layers: 10
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.4104395047795899
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/xb2jzg0p
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 4.676581530548799e-06
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9927571162692338
        grad_clip: 1.4265774065857295
        learning_rate: 0.00037199851654233274
        log_freq: 100
        min_lr: 4.676581530548799e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.7457103064325055
            pretrained: 0.005200413604068712
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.006561635786185183
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.006561635786185183
