_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2607987418207602
aug_joint_noise_std:
    value: 0.009605625667867029
aug_rotation_range:
    value: 22.577629500015533
aug_scale_max:
    value: 1.1183493857093605
aug_scale_min:
    value: 0.7802265799437668
aug_translation_std:
    value: 0.07077860825008493
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.6427108480504311
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.2607987418207602
            joint_noise_std: 0.009605625667867029
            rotation_range: 22.577629500015533
            scale_range:
                - 0.7802265799437668
                - 1.1183493857093605
            translation_std: 0.07077860825008493
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.998986771218476
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_0w7zw45s_20250603_231147
freeze_layers:
    value: 8
grad_clip:
    value: 0.6151981928124841
gradient_checkpointing:
    value: true
hidden_dim:
    value: 1024
learning_rate:
    value: 0.0003621887868913864
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.23562128746843
            diversity: 0.008476830488533328
            hand_coarse: 1.3181988844814836
            hand_refined: 1.6722495245071882
            kl: 0.00036415204760744497
            object_position: 0.9497665495073062
            object_rotation: 0.6657084650159162
            physics: 0.1258064019157527
            reprojection: 0.8848008726198093
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.23562128746843
loss_weight_diversity:
    value: 0.008476830488533328
loss_weight_hand_coarse:
    value: 1.3181988844814836
loss_weight_hand_refined:
    value: 1.6722495245071882
loss_weight_kl:
    value: 0.00036415204760744497
loss_weight_object_position:
    value: 0.9497665495073062
loss_weight_object_rotation:
    value: 0.6657084650159162
loss_weight_physics:
    value: 0.1258064019157527
loss_weight_reprojection:
    value: 0.8848008726198093
lr_mult_new_encoders:
    value: 0.5610375585848466
lr_mult_pretrained:
    value: 0.001058963808259102
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.2
        freeze_layers: 8
        hidden_dim: 1024
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.6427108480504311
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/0w7zw45s
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 9.774669362866837e-07
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.998986771218476
        grad_clip: 0.6151981928124841
        learning_rate: 0.0003621887868913864
        log_freq: 100
        min_lr: 9.774669362866837e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.5610375585848466
            pretrained: 0.001058963808259102
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.019392398001816715
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.019392398001816715
