_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2239770052663983
aug_joint_noise_std:
    value: 0.008897159293693325
aug_rotation_range:
    value: 28.511380869376712
aug_scale_max:
    value: 1.185634563456116
aug_scale_min:
    value: 0.8181665741165448
aug_translation_std:
    value: 0.039216422691957326
batch_size:
    value: 32
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.5222883258210169
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.2239770052663983
            joint_noise_std: 0.008897159293693325
            rotation_range: 28.511380869376712
            scale_range:
                - 0.8181665741165448
                - 1.185634563456116
            translation_std: 0.039216422691957326
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9965953866199144
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_j8c1n12n_20250603_232402
freeze_layers:
    value: 8
grad_clip:
    value: 1.124193784348578
gradient_checkpointing:
    value: false
hidden_dim:
    value: 512
learning_rate:
    value: 0.004104690754275174
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.4851187266477443
            diversity: 0.0023995192240977617
            hand_coarse: 1.932740239447631
            hand_refined: 1.4986932211054038
            kl: 0.0013195842167480951
            object_position: 0.5834509720421592
            object_rotation: 0.31530077113455973
            physics: 0.1836431379948038
            reprojection: 0.8105635456890068
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.4851187266477443
loss_weight_diversity:
    value: 0.0023995192240977617
loss_weight_hand_coarse:
    value: 1.932740239447631
loss_weight_hand_refined:
    value: 1.4986932211054038
loss_weight_kl:
    value: 0.0013195842167480951
loss_weight_object_position:
    value: 0.5834509720421592
loss_weight_object_rotation:
    value: 0.31530077113455973
loss_weight_physics:
    value: 0.1836431379948038
loss_weight_reprojection:
    value: 0.8105635456890068
lr_mult_new_encoders:
    value: 0.688855303924078
lr_mult_pretrained:
    value: 0.03202901717145616
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.3
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.5222883258210169
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/j8c1n12n
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 2.5306261493621115e-06
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 32
        ema_decay: 0.9965953866199144
        grad_clip: 1.124193784348578
        learning_rate: 0.004104690754275174
        log_freq: 100
        min_lr: 2.5306261493621115e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.688855303924078
            pretrained: 0.03202901717145616
        num_epochs: 20
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0017451228718577969
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0017451228718577969
