_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.17568926397004236
aug_joint_noise_std:
    value: 0.0037740879961175233
aug_rotation_range:
    value: 22.480417895317284
aug_scale_max:
    value: 1.2670879021086556
aug_scale_min:
    value: 0.7538906786108622
aug_translation_std:
    value: 0.06274351151735795
batch_size:
    value: 16
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.6664017528402824
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.17568926397004236
            joint_noise_std: 0.0037740879961175233
            rotation_range: 22.480417895317284
            scale_range:
                - 0.7538906786108622
                - 1.2670879021086556
            translation_std: 0.06274351151735795
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.1
ema_decay:
    value: 0.9963449558390144
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_x5yuxqwy_20250603_231216
freeze_layers:
    value: 10
grad_clip:
    value: 1.928343034205548
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 7.952236082449577e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.15792554396569491
            diversity: 0.004437398269363232
            hand_coarse: 0.7697305634070839
            hand_refined: 2.3883729112066314
            kl: 0.00905866793381058
            object_position: 1.5597966163537818
            object_rotation: 0.3136801099680053
            physics: 0.1270254581093757
            reprojection: 0.6864406638897393
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.15792554396569491
loss_weight_diversity:
    value: 0.004437398269363232
loss_weight_hand_coarse:
    value: 0.7697305634070839
loss_weight_hand_refined:
    value: 2.3883729112066314
loss_weight_kl:
    value: 0.00905866793381058
loss_weight_object_position:
    value: 1.5597966163537818
loss_weight_object_rotation:
    value: 0.3136801099680053
loss_weight_physics:
    value: 0.1270254581093757
loss_weight_reprojection:
    value: 0.6864406638897393
lr_mult_new_encoders:
    value: 0.6056462741596997
lr_mult_pretrained:
    value: 0.06102874722730847
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.1
        freeze_layers: 10
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.6664017528402824
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/x5yuxqwy
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 2.2138122370061263e-06
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 16
        ema_decay: 0.9963449558390144
        grad_clip: 1.928343034205548
        learning_rate: 7.952236082449577e-05
        log_freq: 100
        min_lr: 2.2138122370061263e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.6056462741596997
            pretrained: 0.06102874722730847
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.03944313797540561
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.03944313797540561
