_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2115677984511236
aug_joint_noise_std:
    value: 0.004425182437514371
aug_rotation_range:
    value: 13.152195440669692
aug_scale_max:
    value: 1.2796160917387172
aug_scale_min:
    value: 0.7454313710667306
aug_translation_std:
    value: 0.02685651514349128
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.39569332032465626
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.2115677984511236
            joint_noise_std: 0.004425182437514371
            rotation_range: 13.152195440669692
            scale_range:
                - 0.7454313710667306
                - 1.2796160917387172
            translation_std: 0.02685651514349128
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9947186935848972
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_9tkan5jt_20250603_230915
freeze_layers:
    value: 10
grad_clip:
    value: 1.899616463766201
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 0.007385495345735515
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.32744398119911144
            diversity: 0.001804075904454242
            hand_coarse: 1.5659443991886302
            hand_refined: 2.116706457337283
            kl: 0.0003878101623638275
            object_position: 0.8727501110756442
            object_rotation: 0.7486248116219978
            physics: 0.1581025807905228
            reprojection: 0.7497140234184798
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.32744398119911144
loss_weight_diversity:
    value: 0.001804075904454242
loss_weight_hand_coarse:
    value: 1.5659443991886302
loss_weight_hand_refined:
    value: 2.116706457337283
loss_weight_kl:
    value: 0.0003878101623638275
loss_weight_object_position:
    value: 0.8727501110756442
loss_weight_object_rotation:
    value: 0.7486248116219978
loss_weight_physics:
    value: 0.1581025807905228
loss_weight_reprojection:
    value: 0.7497140234184798
lr_mult_new_encoders:
    value: 0.7340972222608688
lr_mult_pretrained:
    value: 0.07656906151244776
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.3
        freeze_layers: 10
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.39569332032465626
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/9tkan5jt
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 2.873743711249417e-07
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.9947186935848972
        grad_clip: 1.899616463766201
        learning_rate: 0.007385495345735515
        log_freq: 100
        min_lr: 2.873743711249417e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.7340972222608688
            pretrained: 0.07656906151244776
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0011463019673982292
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0011463019673982292
