_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.18826801191809203
aug_joint_noise_std:
    value: 0.006971083782617339
aug_rotation_range:
    value: 12.338346795186938
aug_scale_max:
    value: 1.1913908434119418
aug_scale_min:
    value: 0.7412552379071442
aug_translation_std:
    value: 0.04893402046707633
batch_size:
    value: 16
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.44801419261847286
contact_hidden_dim:
    value: 256
data:
    value:
        augmentation:
            color_jitter: 0.18826801191809203
            joint_noise_std: 0.006971083782617339
            rotation_range: 12.338346795186938
            scale_range:
                - 0.7412552379071442
                - 1.1913908434119418
            translation_std: 0.04893402046707633
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.1
ema_decay:
    value: 0.9971780028137258
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_8pogvs0g_20250603_231422
freeze_layers:
    value: 8
grad_clip:
    value: 1.6002219271924158
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 0.0006973121251446997
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.22546653445315357
            diversity: 0.0016284965468366037
            hand_coarse: 0.5963916506491576
            hand_refined: 1.9428187114422375
            kl: 0.0011499545277059893
            object_position: 0.7372620866664915
            object_rotation: 0.21192196347080472
            physics: 0.059518357694031535
            reprojection: 0.7309204762810722
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.22546653445315357
loss_weight_diversity:
    value: 0.0016284965468366037
loss_weight_hand_coarse:
    value: 0.5963916506491576
loss_weight_hand_refined:
    value: 1.9428187114422375
loss_weight_kl:
    value: 0.0011499545277059893
loss_weight_object_position:
    value: 0.7372620866664915
loss_weight_object_rotation:
    value: 0.21192196347080472
loss_weight_physics:
    value: 0.059518357694031535
loss_weight_reprojection:
    value: 0.7309204762810722
lr_mult_new_encoders:
    value: 0.3671741207791828
lr_mult_pretrained:
    value: 0.026494986199123032
model:
    value:
        contact_hidden_dim: 256
        dropout: 0.1
        freeze_layers: 8
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.44801419261847286
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/8pogvs0g
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 4.950540273554913e-07
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 16
        ema_decay: 0.9971780028137258
        grad_clip: 1.6002219271924158
        learning_rate: 0.0006973121251446997
        log_freq: 100
        min_lr: 4.950540273554913e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.3671741207791828
            pretrained: 0.026494986199123032
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.0003717444827923112
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.0003717444827923112
