_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.17505699248205284
aug_joint_noise_std:
    value: 0.006522409743803552
aug_rotation_range:
    value: 15.046218942751628
aug_scale_max:
    value: 1.141379440683567
aug_scale_min:
    value: 0.7477438786035719
aug_translation_std:
    value: 0.05026296143516251
batch_size:
    value: 16
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.41890280091228377
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.17505699248205284
            joint_noise_std: 0.006522409743803552
            rotation_range: 15.046218942751628
            scale_range:
                - 0.7477438786035719
                - 1.141379440683567
            translation_std: 0.05026296143516251
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.2
ema_decay:
    value: 0.9915892962041684
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_s2g8sspn_20250603_233640
freeze_layers:
    value: 12
grad_clip:
    value: 1.5722018733441463
gradient_checkpointing:
    value: false
hidden_dim:
    value: 768
learning_rate:
    value: 0.007233243169405605
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.32563643884644305
            diversity: 0.050280518962524466
            hand_coarse: 0.6161421747357674
            hand_refined: 0.9833304910650283
            kl: 0.0007658471779566368
            object_position: 1.2291177474777977
            object_rotation: 0.21098460572881728
            physics: 0.19466956689469825
            reprojection: 0.9461925529245478
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.32563643884644305
loss_weight_diversity:
    value: 0.050280518962524466
loss_weight_hand_coarse:
    value: 0.6161421747357674
loss_weight_hand_refined:
    value: 0.9833304910650283
loss_weight_kl:
    value: 0.0007658471779566368
loss_weight_object_position:
    value: 1.2291177474777977
loss_weight_object_rotation:
    value: 0.21098460572881728
loss_weight_physics:
    value: 0.19466956689469825
loss_weight_reprojection:
    value: 0.9461925529245478
lr_mult_new_encoders:
    value: 0.705403968072866
lr_mult_pretrained:
    value: 0.0019665406476667324
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.2
        freeze_layers: 12
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 3
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: true
num_refinement_steps:
    value: 3
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.41890280091228377
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/s2g8sspn
scheduler_T_0:
    value: 10
scheduler_min_lr:
    value: 3.822059738968864e-07
training:
    value:
        T_0: 10
        T_mult: 2
        accumulation_steps: 2
        batch_size: 16
        ema_decay: 0.9915892962041684
        grad_clip: 1.5722018733441463
        learning_rate: 0.007233243169405605
        log_freq: 100
        min_lr: 3.822059738968864e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.705403968072866
            pretrained: 0.0019665406476667324
        num_epochs: 20
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.005359219101117648
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: true
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.005359219101117648
