accumulation_steps: 4
batch_size: 256
contact_hidden_dim: 512
grad_clip: 1.0
hand_hidden_dim: 1024
image_size:
- 224
- 224
learning_rate: 0.001
log_interval: 10
num_epochs: 5
num_workers: 16
object_hidden_dim: 1024
patch_size: 16
pin_memory: true
prefetch_factor: 4
use_amp: true
val_interval: 50
