_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2258560850467934
aug_joint_noise_std:
    value: 0.004916951279724713
aug_rotation_range:
    value: 16.842105740028707
aug_scale_max:
    value: 1.278215611303105
aug_scale_min:
    value: 0.8907488776465559
aug_translation_std:
    value: 0.04593799960269254
batch_size:
    value: 16
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.505572668999979
contact_hidden_dim:
    value: 512
data:
    value:
        augmentation:
            color_jitter: 0.2258560850467934
            joint_noise_std: 0.004916951279724713
            rotation_range: 16.842105740028707
            scale_range:
                - 0.8907488776465559
                - 1.278215611303105
            translation_std: 0.04593799960269254
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.9973053020006136
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_gi7f9xnm_20250603_230910
freeze_layers:
    value: 8
grad_clip:
    value: 0.8370337598823221
gradient_checkpointing:
    value: true
hidden_dim:
    value: 768
learning_rate:
    value: 0.0077556010334299584
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.14428332400722033
            diversity: 0.01135354145912232
            hand_coarse: 1.5604888820524891
            hand_refined: 1.8199180271016917
            kl: 0.00018695344618188797
            object_position: 1.558272299451011
            object_rotation: 0.4494579981192181
            physics: 0.16058497116055248
            reprojection: 0.84234106475448
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.14428332400722033
loss_weight_diversity:
    value: 0.01135354145912232
loss_weight_hand_coarse:
    value: 1.5604888820524891
loss_weight_hand_refined:
    value: 1.8199180271016917
loss_weight_kl:
    value: 0.00018695344618188797
loss_weight_object_position:
    value: 1.558272299451011
loss_weight_object_rotation:
    value: 0.4494579981192181
loss_weight_physics:
    value: 0.16058497116055248
loss_weight_reprojection:
    value: 0.84234106475448
lr_mult_new_encoders:
    value: 0.4824564856732992
lr_mult_pretrained:
    value: 0.010841496737379306
model:
    value:
        contact_hidden_dim: 512
        dropout: 0.3
        freeze_layers: 8
        hidden_dim: 768
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 2
        use_attention_fusion: false
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 2
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.505572668999979
            dynamic_batch_sizing: true
            gradient_checkpointing: true
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/gi7f9xnm
scheduler_T_0:
    value: 5
scheduler_min_lr:
    value: 1.7790959569649258e-07
training:
    value:
        T_0: 5
        T_mult: 2
        accumulation_steps: 2
        batch_size: 16
        ema_decay: 0.9973053020006136
        grad_clip: 0.8370337598823221
        learning_rate: 0.0077556010334299584
        log_freq: 100
        min_lr: 1.7790959569649258e-07
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.4824564856732992
            pretrained: 0.010841496737379306
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.00028699370676176503
use_amp:
    value: true
use_attention_fusion:
    value: false
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.00028699370676176503
