_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 11
                - 49
                - 55
            "2":
                - 1
                - 11
                - 49
                - 55
            "3":
                - 2
                - 14
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "6": 4.36.0
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
aug_color_jitter:
    value: 0.2983486011272441
aug_joint_noise_std:
    value: 0.003824604334319237
aug_rotation_range:
    value: 14.028806924203074
aug_scale_max:
    value: 1.1726792399131576
aug_scale_min:
    value: 0.8640875262449733
aug_translation_std:
    value: 0.0744523624763987
batch_size:
    value: 64
checkpoint:
    value:
        checkpoint_dir: ${output_dir}/checkpoints
        resume_from: null
checkpoint_ratio:
    value: 0.3822443963120423
contact_hidden_dim:
    value: 768
data:
    value:
        augmentation:
            color_jitter: 0.2983486011272441
            joint_noise_std: 0.003824604334319237
            rotation_range: 14.028806924203074
            scale_range:
                - 0.8640875262449733
                - 1.1726792399131576
            translation_std: 0.0744523624763987
        dexycb_root: ../dex-ycb-toolkit
        num_workers: 8
        persistent_workers: true
        prefetch_factor: 4
        root_dir: ../dex-ycb-toolkit
        sequence_length: 1
        train_split: s0_train
        val_split: s0_val
debug:
    value:
        debug_final_model: true
        debug_initial_model: true
        enabled: false
        log_gradient_norms: true
        save_attention_maps: false
dropout:
    value: 0.3
ema_decay:
    value: 0.991838657095566
evaluation:
    value:
        metrics:
            - mpjpe
            - pa_mpjpe
            - pck_2d
            - pck_3d
        pck_thresholds:
            - 20
            - 30
            - 40
            - 50
        save_visualizations: true
experiment_name:
    value: sweep_x7oflxbk_20250603_231253
freeze_layers:
    value: 8
grad_clip:
    value: 0.968597879794123
gradient_checkpointing:
    value: false
hidden_dim:
    value: 512
learning_rate:
    value: 2.2962702489882577e-05
loss:
    value:
        diversity_margin: 0.01
        fingertip_weight: 1.5
        loss_weights:
            contact: 0.260730203353833
            diversity: 0.019842291140715618
            hand_coarse: 0.9819134569867244
            hand_refined: 1.115059040537694
            kl: 0.0016628916731086282
            object_position: 1.9579667107377905
            object_rotation: 0.6827185513575889
            physics: 0.17120369433897364
            reprojection: 0.9480778308705048
        object_position_weight: 1
        per_joint_weighting: true
loss_weight_contact:
    value: 0.260730203353833
loss_weight_diversity:
    value: 0.019842291140715618
loss_weight_hand_coarse:
    value: 0.9819134569867244
loss_weight_hand_refined:
    value: 1.115059040537694
loss_weight_kl:
    value: 0.0016628916731086282
loss_weight_object_position:
    value: 1.9579667107377905
loss_weight_object_rotation:
    value: 0.6827185513575889
loss_weight_physics:
    value: 0.17120369433897364
loss_weight_reprojection:
    value: 0.9480778308705048
lr_mult_new_encoders:
    value: 0.7439798877276813
lr_mult_pretrained:
    value: 0.06254857258534001
model:
    value:
        contact_hidden_dim: 768
        dropout: 0.3
        freeze_layers: 8
        hidden_dim: 512
        max_objects: 10
        num_contact_points: 10
        num_object_classes: 100
        num_refinement_steps: 1
        use_attention_fusion: true
        use_mano_vertices: true
        use_sigma_reparam: false
num_refinement_steps:
    value: 1
optimizations:
    value:
        memory:
            checkpoint_ratio: 0.3822443963120423
            dynamic_batch_sizing: true
            gradient_checkpointing: false
            target_memory_usage: 0.9
        use_flash_attention: true
        use_fp8: false
        use_fsdp: false
        use_memory_optimization: true
        use_mode_collapse_prevention: true
output_dir:
    value: outputs/sweeps/x7oflxbk
scheduler_T_0:
    value: 20
scheduler_min_lr:
    value: 9.31061418298601e-06
training:
    value:
        T_0: 20
        T_mult: 2
        accumulation_steps: 2
        batch_size: 64
        ema_decay: 0.991838657095566
        grad_clip: 0.968597879794123
        learning_rate: 2.2962702489882577e-05
        log_freq: 100
        min_lr: 9.31061418298601e-06
        mixed_precision: true
        multi_rate:
            decoders: 1
            new_encoders: 0.7439798877276813
            pretrained: 0.06254857258534001
        num_epochs: 100
        save_freq: 10
        scheduler: cosine
        use_amp: true
        use_bf16: true
        use_ema: true
        use_wandb: true
        val_freq: 1000
        weight_decay: 0.01964914479787728
use_amp:
    value: true
use_attention_fusion:
    value: true
use_bf16:
    value: true
use_sigma_reparam:
    value: false
wandb_project:
    value: 231nProject_AMT
weight_decay:
    value: 0.01964914479787728
